// أكواد DTC إضافية - P1xxx + P2xxx + P3xxx + B1xxx + C1xxx
// إجمالي: 305 كود جديد

import { MegaDTCEntry } from './dtcMegaDatabase';

export const ADDITIONAL_DTC_DATABASE: Record<string, MegaDTCEntry> = {
  // ═══ P1xxx - أكواد المصنّع الشائعة (نيسان، تويوتا، فورد، جي إم، هيونداي) ═══
  "P1000": { code: "P1000", description: "لم يكتمل فحص OBD-II - فورد", severity: "low", fix: "قيادة السيارة لإكمال دورة الفحص", module: "engine" },
  "P1101": { code: "P1101", description: "عطل في حساس MAF خارج النطاق - فورد", severity: "high", fix: "تنظيف أو استبدال حساس MAF", module: "engine" },
  "P1105": { code: "P1105", description: "عطل في حساس MAP/BARO - نيسان", severity: "high", fix: "فحص واستبدال حساس MAP", module: "engine" },
  "P1110": { code: "P1110", description: "عطل في صمام التحكم بالهواء الثانوي - نيسان", severity: "medium", fix: "فحص صمام الهواء الثانوي", module: "engine" },
  "P1120": { code: "P1120", description: "عطل في حساس TPS الثانوي - نيسان", severity: "high", fix: "فحص واستبدال حساس TPS", module: "engine" },
  "P1121": { code: "P1121", description: "عطل في حساس TPS - هيونداي", severity: "high", fix: "فحص واستبدال حساس TPS", module: "engine" },
  "P1125": { code: "P1125", description: "عطل في نظام الخانق الإلكتروني - نيسان", severity: "high", fix: "فحص جسم الخانق الإلكتروني والأسلاك", module: "engine" },
  "P1130": { code: "P1130", description: "عطل في نسبة الوقود/الهواء بنك1 - نيسان", severity: "high", fix: "فحص حساسات O2 ونظام الوقود", module: "engine" },
  "P1131": { code: "P1131", description: "خليط فقير بنك1 - فورد", severity: "high", fix: "فحص تسريب الهواء وحساس O2", module: "engine" },
  "P1132": { code: "P1132", description: "خليط غني بنك1 - فورد", severity: "high", fix: "فحص الحاقنات ومنظم ضغط الوقود", module: "engine" },
  "P1133": { code: "P1133", description: "استجابة بطيئة من حساس O2 بنك1 - GM", severity: "medium", fix: "استبدال حساس O2", module: "engine" },
  "P1135": { code: "P1135", description: "عطل في سخان حساس A/F بنك1 - نيسان", severity: "medium", fix: "استبدال حساس A/F", module: "engine" },
  "P1140": { code: "P1140", description: "عطل في صمام التحكم بالهواء الخامل IACV - نيسان", severity: "medium", fix: "تنظيف أو استبدال صمام IACV", module: "engine" },
  "P1145": { code: "P1145", description: "عطل في نظام VVT بنك1 - نيسان", severity: "high", fix: "فحص صمام VVT وزيت المحرك", module: "engine" },
  "P1148": { code: "P1148", description: "عطل في نظام التحكم بالوقود المغلق بنك1 - نيسان", severity: "high", fix: "فحص حساسات O2 ونظام الوقود", module: "engine" },
  "P1151": { code: "P1151", description: "خليط فقير بنك2 - فورد", severity: "high", fix: "فحص تسريب الهواء بنك2", module: "engine" },
  "P1152": { code: "P1152", description: "خليط غني بنك2 - فورد", severity: "high", fix: "فحص الحاقنات بنك2", module: "engine" },
  "P1153": { code: "P1153", description: "استجابة بطيئة من حساس O2 بنك2 - GM", severity: "medium", fix: "استبدال حساس O2 بنك2", module: "engine" },
  "P1159": { code: "P1159", description: "عطل في حساس A/F بنك2 - هيونداي", severity: "high", fix: "استبدال حساس A/F", module: "engine" },
  "P1165": { code: "P1165", description: "عطل في نسبة الوقود/الهواء بنك2 - نيسان", severity: "high", fix: "فحص حساسات O2 بنك2", module: "engine" },
  "P1166": { code: "P1166", description: "عطل في سخان حساس A/F بنك2 - هيونداي", severity: "medium", fix: "استبدال حساس A/F بنك2", module: "engine" },
  "P1168": { code: "P1168", description: "عطل في نظام التحكم بالوقود المغلق بنك2 - نيسان", severity: "high", fix: "فحص حساسات O2 بنك2 ونظام الوقود", module: "engine" },
  "P1174": { code: "P1174", description: "نظام الوقود فقير بنك1 - GM", severity: "high", fix: "فحص تسريب الهواء والحاقنات", module: "engine" },
  "P1175": { code: "P1175", description: "نظام الوقود فقير بنك2 - GM", severity: "high", fix: "فحص تسريب الهواء بنك2", module: "engine" },
  "P1195": { code: "P1195", description: "عطل في حساس EGR - هيونداي", severity: "medium", fix: "فحص حساس EGR", module: "engine" },
  "P1210": { code: "P1210", description: "عطل في نظام حقن الوقود - نيسان", severity: "high", fix: "فحص مضخة الوقود والحاقنات", module: "engine" },
  "P1211": { code: "P1211", description: "عطل في نظام التحكم بالسرعة الخاملة - نيسان", severity: "medium", fix: "فحص صمام IACV", module: "engine" },
  "P1217": { code: "P1217", description: "ارتفاع حرارة المحرك - نيسان", severity: "critical", fix: "فحص نظام التبريد فوراً", module: "engine" },
  "P1220": { code: "P1220", description: "عطل في حساس TPS - نيسان", severity: "high", fix: "فحص واستبدال حساس TPS", module: "engine" },
  "P1233": { code: "P1233", description: "عطل في مضخة الوقود - لا إشارة - فورد", severity: "high", fix: "فحص ريلاي ومضخة الوقود", module: "engine" },
  "P1234": { code: "P1234", description: "عطل في مضخة الوقود - تعطل - فورد", severity: "critical", fix: "استبدال مضخة الوقود", module: "engine" },
  "P1235": { code: "P1235", description: "عطل في التحكم بمضخة الوقود - فورد", severity: "high", fix: "فحص دائرة مضخة الوقود", module: "engine" },
  "P1236": { code: "P1236", description: "عطل في التحكم بمضخة الوقود - خارج النطاق - فورد", severity: "high", fix: "فحص ضغط الوقود", module: "engine" },
  "P1258": { code: "P1258", description: "ارتفاع حرارة المحرك - تم تقليل الطاقة - GM", severity: "critical", fix: "فحص نظام التبريد فوراً", module: "engine" },
  "P1260": { code: "P1260", description: "تم تفعيل نظام منع السرقة PATS - فورد", severity: "high", fix: "إعادة برمجة مفتاح PATS", module: "engine" },
  "P1270": { code: "P1270", description: "تم تحديد سرعة المحرك بسبب عطل - فورد", severity: "high", fix: "فحص الأعطال الأخرى أولاً", module: "engine" },
  "P1285": { code: "P1285", description: "ارتفاع حرارة رأس المحرك CHT - فورد", severity: "critical", fix: "فحص نظام التبريد فوراً", module: "engine" },
  "P1295": { code: "P1295", description: "عطل في نظام الخانق الإلكتروني ETS - هيونداي", severity: "high", fix: "فحص جسم الخانق", module: "engine" },
  "P1299": { code: "P1299", description: "ارتفاع حرارة المحرك - تم تقليل الطاقة - فورد", severity: "critical", fix: "إيقاف السيارة وفحص التبريد فوراً", module: "engine" },
  "P1300": { code: "P1300", description: "عطل في دائرة الإشعال رقم 1 - تويوتا", severity: "high", fix: "فحص كويل الإشعال رقم 1", module: "engine" },
  "P1305": { code: "P1305", description: "عطل في دائرة الإشعال رقم 2 - تويوتا", severity: "high", fix: "فحص كويل الإشعال رقم 2", module: "engine" },
  "P1309": { code: "P1309", description: "عطل في نظام كشف اختلال الإشعال - فورد", severity: "high", fix: "فحص شمعات الإشعال والكويلات", module: "engine" },
  "P1310": { code: "P1310", description: "عطل في دائرة الإشعال رقم 3 - تويوتا", severity: "high", fix: "فحص كويل الإشعال رقم 3", module: "engine" },
  "P1315": { code: "P1315", description: "عطل في دائرة الإشعال رقم 4 - تويوتا", severity: "high", fix: "فحص كويل الإشعال رقم 4", module: "engine" },
  "P1316": { code: "P1316", description: "اختلال إشعال مع انخفاض الوقود - فورد", severity: "high", fix: "فحص الحاقنات والوقود", module: "engine" },
  "P1320": { code: "P1320", description: "عطل في دائرة الإشعال - نيسان", severity: "high", fix: "فحص الكويلات وشمعات الإشعال", module: "engine" },
  "P1335": { code: "P1335", description: "عطل في حساس عمود الكرنك CKP - نيسان", severity: "high", fix: "فحص واستبدال حساس CKP", module: "engine" },
  "P1336": { code: "P1336", description: "عطل في حساس عمود الكامات CMP - نيسان", severity: "high", fix: "فحص واستبدال حساس CMP", module: "engine" },
  "P1345": { code: "P1345", description: "عطل في ارتباط حساس CKP/CMP - GM", severity: "high", fix: "فحص سلسلة التوقيت وحساسات CKP/CMP", module: "engine" },
  "P1346": { code: "P1346", description: "عطل في نظام VVT-i - تويوتا", severity: "high", fix: "فحص صمام VVT-i وزيت المحرك", module: "engine" },
  "P1349": { code: "P1349", description: "عطل في نظام VVT-i بنك2 - تويوتا", severity: "high", fix: "فحص صمام VVT-i بنك2", module: "engine" },
  "P1351": { code: "P1351", description: "عطل في دائرة الإشعال - جهد مرتفع - تويوتا", severity: "high", fix: "فحص نظام الإشعال", module: "engine" },
  "P1380": { code: "P1380", description: "عطل في نظام ABS/TCS - GM", severity: "high", fix: "فحص نظام ABS", module: "abs" },
  "P1386": { code: "P1386", description: "عطل في حساس الطرق بنك2 - هيونداي", severity: "medium", fix: "فحص حساس الطرق", module: "engine" },
  "P1400": { code: "P1400", description: "عطل في نظام EGR - نيسان", severity: "medium", fix: "تنظيف أو استبدال صمام EGR", module: "engine" },
  "P1401": { code: "P1401", description: "عطل في حساس درجة حرارة EGR - نيسان", severity: "medium", fix: "فحص حساس EGR", module: "engine" },
  "P1402": { code: "P1402", description: "عطل في صمام EGR - نيسان", severity: "medium", fix: "استبدال صمام EGR", module: "engine" },
  "P1404": { code: "P1404", description: "عطل في صمام EGR - عالق مفتوح - GM", severity: "medium", fix: "تنظيف أو استبدال صمام EGR", module: "engine" },
  "P1440": { code: "P1440", description: "عطل في نظام EVAP - تسريب صغير - نيسان", severity: "low", fix: "فحص غطاء الوقود وخراطيم EVAP", module: "engine" },
  "P1441": { code: "P1441", description: "عطل في صمام تنفيس EVAP - نيسان", severity: "low", fix: "استبدال صمام تنفيس EVAP", module: "engine" },
  "P1443": { code: "P1443", description: "عطل في صمام تطهير EVAP - نيسان", severity: "low", fix: "استبدال صمام تطهير EVAP", module: "engine" },
  "P1445": { code: "P1445", description: "عطل في صمام تنفيس خزان الوقود - نيسان", severity: "low", fix: "فحص صمام التنفيس", module: "engine" },
  "P1450": { code: "P1450", description: "عطل في نظام EVAP - ضغط زائد - فورد", severity: "medium", fix: "فحص صمام تنفيس EVAP", module: "engine" },
  "P1451": { code: "P1451", description: "عطل في صمام تنفيس EVAP - فورد", severity: "medium", fix: "استبدال صمام تنفيس EVAP", module: "engine" },
  "P1460": { code: "P1460", description: "عطل في مروحة التبريد - فورد", severity: "high", fix: "فحص ريلاي ومروحة التبريد", module: "engine" },
  "P1464": { code: "P1464", description: "عطل في مروحة التبريد - سرعة منخفضة - فورد", severity: "medium", fix: "فحص مقاومة المروحة", module: "engine" },
  "P1474": { code: "P1474", description: "عطل في مروحة التبريد - سرعة عالية - فورد", severity: "medium", fix: "فحص ريلاي السرعة العالية", module: "engine" },
  "P1490": { code: "P1490", description: "عطل في صمام التحكم بالفراغ - نيسان", severity: "medium", fix: "فحص صمام الفراغ", module: "engine" },
  "P1491": { code: "P1491", description: "عطل في صمام التحكم بالفراغ الثانوي - نيسان", severity: "medium", fix: "فحص صمام الفراغ الثانوي", module: "engine" },
  "P1500": { code: "P1500", description: "عطل في دائرة بدء التشغيل - فورد", severity: "high", fix: "فحص المارش والأسلاك", module: "engine" },
  "P1504": { code: "P1504", description: "عطل في صمام IAC - فورد", severity: "medium", fix: "تنظيف أو استبدال صمام IAC", module: "engine" },
  "P1505": { code: "P1505", description: "عطل في صمام IAC - هيونداي", severity: "medium", fix: "تنظيف أو استبدال IAC", module: "engine" },
  "P1506": { code: "P1506", description: "سرعة خاملة مرتفعة - فورد", severity: "medium", fix: "فحص تسريب الهواء وصمام IAC", module: "engine" },
  "P1507": { code: "P1507", description: "سرعة خاملة منخفضة - فورد", severity: "medium", fix: "فحص صمام IAC وتسريب الفراغ", module: "engine" },
  "P1510": { code: "P1510", description: "عطل في صمام IAC - تويوتا", severity: "medium", fix: "تنظيف أو استبدال صمام IAC", module: "engine" },
  "P1516": { code: "P1516", description: "عطل في نظام TAC (خانق إلكتروني) - GM", severity: "high", fix: "فحص جسم الخانق الإلكتروني", module: "engine" },
  "P1518": { code: "P1518", description: "عطل في نظام TAC - موضع غير صحيح - GM", severity: "high", fix: "إعادة تعلم الخانق", module: "engine" },
  "P1520": { code: "P1520", description: "عطل في مفتاح التوقف - تويوتا", severity: "medium", fix: "فحص مفتاح الفرامل", module: "engine" },
  "P1523": { code: "P1523", description: "عطل في صمام VTEC - هيونداي", severity: "high", fix: "فحص صمام VTEC وزيت المحرك", module: "engine" },
  "P1550": { code: "P1550", description: "عطل في صمام التحكم بالسرعة الخاملة - نيسان", severity: "medium", fix: "تنظيف أو استبدال صمام IAC", module: "engine" },
  "P1600": { code: "P1600", description: "عطل في وحدة ECM - تويوتا", severity: "high", fix: "فحص وإعادة برمجة ECM", module: "engine" },
  "P1605": { code: "P1605", description: "عطل في ذاكرة ECM - تويوتا", severity: "high", fix: "إعادة برمجة ECM", module: "engine" },
  "P1610": { code: "P1610", description: "عطل في نظام منع السرقة NATS - نيسان", severity: "high", fix: "إعادة برمجة مفتاح NATS", module: "engine" },
  "P1612": { code: "P1612", description: "عطل في نظام NATS - المفتاح غير معرّف - نيسان", severity: "high", fix: "برمجة مفتاح جديد عبر CONSULT", module: "engine" },
  "P1614": { code: "P1614", description: "عطل في نظام NATS - خطأ ECM - نيسان", severity: "high", fix: "إعادة برمجة ECM ومفتاح NATS", module: "engine" },
  "P1621": { code: "P1621", description: "عطل في ذاكرة PCM - GM", severity: "high", fix: "إعادة برمجة PCM", module: "engine" },
  "P1624": { code: "P1624", description: "عطل في مروحة التبريد - هيونداي", severity: "high", fix: "فحص ريلاي المروحة", module: "engine" },
  "P1626": { code: "P1626", description: "عطل في نظام منع السرقة - GM", severity: "high", fix: "إعادة برمجة المفتاح", module: "engine" },
  "P1633": { code: "P1633", description: "عطل في ذاكرة KAM - فورد", severity: "medium", fix: "فحص البطارية وإعادة تعيين KAM", module: "engine" },
  "P1656": { code: "P1656", description: "عطل في صمام التحكم بزيت VVT - تويوتا", severity: "high", fix: "استبدال صمام OCV", module: "engine" },
  "P1682": { code: "P1682", description: "عطل في دائرة التحكم بالإشعال - GM", severity: "high", fix: "فحص ريلاي الإشعال", module: "engine" },
  "P1693": { code: "P1693", description: "عطل في شبكة CAN - هيونداي", severity: "high", fix: "فحص أسلاك CAN Bus", module: "network" },
  "P1700": { code: "P1700", description: "عطل في حساس سرعة القير - نيسان", severity: "high", fix: "فحص حساس سرعة القير", module: "transmission" },
  "P1705": { code: "P1705", description: "عطل في حساس وضع القير - نيسان", severity: "high", fix: "فحص حساس وضع القير", module: "transmission" },
  "P1706": { code: "P1706", description: "عطل في مفتاح Park/Neutral - نيسان", severity: "medium", fix: "فحص مفتاح P/N", module: "transmission" },
  "P1744": { code: "P1744", description: "عطل في قابض محول العزم TCC - فورد", severity: "high", fix: "فحص صمام TCC وزيت القير", module: "transmission" },
  "P1747": { code: "P1747", description: "عطل في صمام ضغط القير EPC - فورد", severity: "high", fix: "فحص صمام EPC", module: "transmission" },
  "P1760": { code: "P1760", description: "عطل في صمام الضغط - نيسان", severity: "high", fix: "فحص صمامات القير", module: "transmission" },
  "P1800": { code: "P1800", description: "عطل في نظام التحكم بالقير CVT - نيسان", severity: "high", fix: "فحص نظام CVT", module: "transmission" },
  "P1810": { code: "P1810", description: "عطل في مفتاح ضغط القير TFP - GM", severity: "high", fix: "فحص مفتاح TFP", module: "transmission" },
  "P1860": { code: "P1860", description: "عطل في صمام TCC - GM", severity: "high", fix: "فحص صمام TCC وزيت القير", module: "transmission" },
  "P1870": { code: "P1870", description: "انزلاق في محول العزم TCC - GM", severity: "high", fix: "فحص زيت القير وصمام TCC", module: "transmission" },
  // ═══ P2xxx - أكواد عامة متقدمة (SAE J2012) ═══
  "P2000": { code: "P2000", description: "كفاءة مصيدة NOx أقل من الحد - بنك1", severity: "high", fix: "فحص أو استبدال مصيدة NOx", module: "engine" },
  "P2002": { code: "P2002", description: "كفاءة فلتر DPF أقل من الحد - بنك1", severity: "high", fix: "تجديد أو استبدال فلتر DPF", module: "engine" },
  "P2004": { code: "P2004", description: "عطل في صمام IMRC - عالق مفتوح - بنك1", severity: "medium", fix: "فحص صمام IMRC", module: "engine" },
  "P2006": { code: "P2006", description: "عطل في صمام IMRC - عالق مغلق - بنك1", severity: "medium", fix: "فحص صمام IMRC", module: "engine" },
  "P2008": { code: "P2008", description: "عطل في دائرة صمام IMRC - بنك1", severity: "medium", fix: "فحص أسلاك صمام IMRC", module: "engine" },
  "P2015": { code: "P2015", description: "عطل في حساس موضع مشعب السحب - بنك1", severity: "high", fix: "فحص حساس موضع المشعب", module: "engine" },
  "P2017": { code: "P2017", description: "عطل في حساس موضع مشعب السحب - بنك2", severity: "high", fix: "فحص حساس موضع المشعب بنك2", module: "engine" },
  "P2088": { code: "P2088", description: "عطل في صمام VVT - موضع A - بنك1", severity: "high", fix: "فحص صمام VVT وزيت المحرك", module: "engine" },
  "P2089": { code: "P2089", description: "عطل في صمام VVT - موضع B - بنك1", severity: "high", fix: "فحص صمام VVT", module: "engine" },
  "P2090": { code: "P2090", description: "عطل في صمام VVT - موضع A - بنك2", severity: "high", fix: "فحص صمام VVT بنك2", module: "engine" },
  "P2091": { code: "P2091", description: "عطل في صمام VVT - موضع B - بنك2", severity: "high", fix: "فحص صمام VVT بنك2", module: "engine" },
  "P2096": { code: "P2096", description: "خليط فقير بعد الكاتاليتك - بنك1", severity: "medium", fix: "فحص حساس O2 والكاتاليتك", module: "engine" },
  "P2097": { code: "P2097", description: "خليط غني بعد الكاتاليتك - بنك1", severity: "medium", fix: "فحص حساس O2 والحاقنات", module: "engine" },
  "P2098": { code: "P2098", description: "خليط فقير بعد الكاتاليتك - بنك2", severity: "medium", fix: "فحص حساس O2 بنك2", module: "engine" },
  "P2099": { code: "P2099", description: "خليط غني بعد الكاتاليتك - بنك2", severity: "medium", fix: "فحص حساس O2 بنك2 والحاقنات", module: "engine" },
  "P2100": { code: "P2100", description: "عطل في دائرة محرك الخانق الإلكتروني", severity: "high", fix: "فحص جسم الخانق والأسلاك", module: "engine" },
  "P2101": { code: "P2101", description: "أداء محرك الخانق الإلكتروني خارج النطاق", severity: "high", fix: "تنظيف أو استبدال جسم الخانق", module: "engine" },
  "P2102": { code: "P2102", description: "عطل في محرك الخانق - إشارة منخفضة", severity: "high", fix: "فحص أسلاك جسم الخانق", module: "engine" },
  "P2103": { code: "P2103", description: "عطل في محرك الخانق - إشارة مرتفعة", severity: "high", fix: "فحص أسلاك جسم الخانق", module: "engine" },
  "P2104": { code: "P2104", description: "نظام الخانق - تم فرض وضع الخمول", severity: "high", fix: "فحص جسم الخانق وحساسات TPS", module: "engine" },
  "P2105": { code: "P2105", description: "نظام الخانق - تم فرض إيقاف المحرك", severity: "critical", fix: "فحص جسم الخانق فوراً", module: "engine" },
  "P2106": { code: "P2106", description: "نظام الخانق - تم تقييد الأداء", severity: "high", fix: "فحص جسم الخانق وحساسات APP", module: "engine" },
  "P2107": { code: "P2107", description: "عطل في وحدة التحكم بالخانق", severity: "high", fix: "فحص وإعادة برمجة وحدة TAC", module: "engine" },
  "P2108": { code: "P2108", description: "عطل في وحدة التحكم بالخانق - أداء", severity: "high", fix: "فحص وحدة TAC", module: "engine" },
  "P2110": { code: "P2110", description: "نظام الخانق - تم تحديد RPM", severity: "high", fix: "فحص جسم الخانق", module: "engine" },
  "P2111": { code: "P2111", description: "نظام الخانق - عالق مفتوح", severity: "high", fix: "تنظيف أو استبدال جسم الخانق", module: "engine" },
  "P2112": { code: "P2112", description: "نظام الخانق - عالق مغلق", severity: "high", fix: "تنظيف أو استبدال جسم الخانق", module: "engine" },
  "P2118": { code: "P2118", description: "عطل في تيار محرك الخانق - خارج النطاق", severity: "high", fix: "فحص جسم الخانق والأسلاك", module: "engine" },
  "P2119": { code: "P2119", description: "عطل في أداء جسم الخانق", severity: "high", fix: "تنظيف أو استبدال جسم الخانق", module: "engine" },
  "P2120": { code: "P2120", description: "عطل في حساس دواسة الوقود APP - دائرة D", severity: "high", fix: "فحص حساس دواسة الوقود", module: "engine" },
  "P2121": { code: "P2121", description: "عطل في حساس APP - أداء خارج النطاق D", severity: "high", fix: "فحص حساس دواسة الوقود", module: "engine" },
  "P2122": { code: "P2122", description: "عطل في حساس APP - إشارة منخفضة D", severity: "high", fix: "فحص أسلاك دواسة الوقود", module: "engine" },
  "P2123": { code: "P2123", description: "عطل في حساس APP - إشارة مرتفعة D", severity: "high", fix: "فحص أسلاك دواسة الوقود", module: "engine" },
  "P2125": { code: "P2125", description: "عطل في حساس دواسة الوقود APP - دائرة E", severity: "high", fix: "فحص حساس دواسة الوقود", module: "engine" },
  "P2127": { code: "P2127", description: "عطل في حساس APP - إشارة منخفضة E", severity: "high", fix: "فحص أسلاك دواسة الوقود", module: "engine" },
  "P2128": { code: "P2128", description: "عطل في حساس APP - إشارة مرتفعة E", severity: "high", fix: "فحص أسلاك دواسة الوقود", module: "engine" },
  "P2135": { code: "P2135", description: "عدم تطابق حساسات TPS A/B", severity: "high", fix: "استبدال جسم الخانق", module: "engine" },
  "P2138": { code: "P2138", description: "عدم تطابق حساسات APP D/E", severity: "high", fix: "استبدال دواسة الوقود", module: "engine" },
  "P2176": { code: "P2176", description: "لم يتم تعلم وضع الخمول بعد", severity: "medium", fix: "إعادة تعلم الخانق", module: "engine" },
  "P2177": { code: "P2177", description: "خليط فقير عند RPM منخفض - بنك1", severity: "high", fix: "فحص تسريب الهواء والحاقنات", module: "engine" },
  "P2178": { code: "P2178", description: "خليط غني عند RPM منخفض - بنك1", severity: "high", fix: "فحص الحاقنات ومنظم الوقود", module: "engine" },
  "P2179": { code: "P2179", description: "خليط فقير عند RPM منخفض - بنك2", severity: "high", fix: "فحص تسريب الهواء بنك2", module: "engine" },
  "P2180": { code: "P2180", description: "خليط غني عند RPM منخفض - بنك2", severity: "high", fix: "فحص الحاقنات بنك2", module: "engine" },
  "P2181": { code: "P2181", description: "عطل في نظام التبريد - أداء", severity: "high", fix: "فحص الترموستات ونظام التبريد", module: "engine" },
  "P2182": { code: "P2182", description: "عطل في حساس حرارة سائل التبريد ECT - دائرة 2", severity: "medium", fix: "فحص حساس ECT", module: "engine" },
  "P2183": { code: "P2183", description: "عطل في حساس ECT - أداء دائرة 2", severity: "medium", fix: "فحص حساس ECT", module: "engine" },
  "P2185": { code: "P2185", description: "عطل في حساس ECT - إشارة مرتفعة دائرة 2", severity: "medium", fix: "فحص أسلاك حساس ECT", module: "engine" },
  "P2187": { code: "P2187", description: "خليط فقير عند الخمول - بنك1", severity: "high", fix: "فحص تسريب الهواء", module: "engine" },
  "P2188": { code: "P2188", description: "خليط غني عند الخمول - بنك1", severity: "high", fix: "فحص الحاقنات", module: "engine" },
  "P2189": { code: "P2189", description: "خليط فقير عند الخمول - بنك2", severity: "high", fix: "فحص تسريب الهواء بنك2", module: "engine" },
  "P2190": { code: "P2190", description: "خليط غني عند الخمول - بنك2", severity: "high", fix: "فحص الحاقنات بنك2", module: "engine" },
  "P2195": { code: "P2195", description: "حساس O2 عالق على Lean - بنك1 حساس1", severity: "high", fix: "فحص تسريب الهواء واستبدال O2", module: "engine" },
  "P2196": { code: "P2196", description: "حساس O2 عالق على Rich - بنك1 حساس1", severity: "high", fix: "فحص الحاقنات واستبدال O2", module: "engine" },
  "P2197": { code: "P2197", description: "حساس O2 عالق على Lean - بنك2 حساس1", severity: "high", fix: "فحص تسريب الهواء بنك2", module: "engine" },
  "P2198": { code: "P2198", description: "حساس O2 عالق على Rich - بنك2 حساس1", severity: "high", fix: "فحص الحاقنات بنك2", module: "engine" },
  "P2227": { code: "P2227", description: "عطل في حساس الضغط الجوي BARO", severity: "medium", fix: "فحص حساس BARO", module: "engine" },
  "P2228": { code: "P2228", description: "عطل في حساس BARO - إشارة منخفضة", severity: "medium", fix: "فحص أسلاك حساس BARO", module: "engine" },
  "P2229": { code: "P2229", description: "عطل في حساس BARO - إشارة مرتفعة", severity: "medium", fix: "فحص أسلاك حساس BARO", module: "engine" },
  "P2231": { code: "P2231", description: "عطل في دائرة حساس O2 - قصر في السخان بنك1 حساس1", severity: "high", fix: "استبدال حساس O2", module: "engine" },
  "P2237": { code: "P2237", description: "عطل في دائرة حساس O2 - تيار إيجابي بنك1 حساس1", severity: "high", fix: "استبدال حساس O2", module: "engine" },
  "P2240": { code: "P2240", description: "عطل في دائرة حساس O2 - تيار إيجابي بنك2 حساس1", severity: "high", fix: "استبدال حساس O2", module: "engine" },
  "P2243": { code: "P2243", description: "عطل في جهد مرجعي حساس O2 - بنك1 حساس1", severity: "high", fix: "فحص أسلاك حساس O2", module: "engine" },
  "P2251": { code: "P2251", description: "عطل في دائرة حساس O2 - تيار سلبي بنك1 حساس1", severity: "high", fix: "استبدال حساس O2", module: "engine" },
  "P2254": { code: "P2254", description: "عطل في دائرة حساس O2 - تيار سلبي بنك2 حساس1", severity: "high", fix: "استبدال حساس O2", module: "engine" },
  "P2261": { code: "P2261", description: "عطل في صمام Turbo Bypass - ميكانيكي", severity: "high", fix: "فحص صمام التوربو", module: "engine" },
  "P2262": { code: "P2262", description: "عطل في ضغط التوربو - لا يتطابق مع المطلوب", severity: "high", fix: "فحص التوربو والصمامات", module: "engine" },
  "P2263": { code: "P2263", description: "عطل في أداء التوربو/الشاحن", severity: "high", fix: "فحص التوربو والأنابيب", module: "engine" },
  "P2270": { code: "P2270", description: "حساس O2 عالق على Lean - بنك1 حساس2", severity: "medium", fix: "فحص الكاتاليتك وحساس O2", module: "engine" },
  "P2271": { code: "P2271", description: "حساس O2 عالق على Rich - بنك1 حساس2", severity: "medium", fix: "فحص الكاتاليتك وحساس O2", module: "engine" },
  "P2272": { code: "P2272", description: "حساس O2 عالق على Lean - بنك2 حساس2", severity: "medium", fix: "فحص الكاتاليتك بنك2", module: "engine" },
  "P2273": { code: "P2273", description: "حساس O2 عالق على Rich - بنك2 حساس2", severity: "medium", fix: "فحص الكاتاليتك بنك2", module: "engine" },
  "P2279": { code: "P2279", description: "تسريب هواء في نظام السحب", severity: "high", fix: "فحص خراطيم السحب والجوانات", module: "engine" },
  "P2291": { code: "P2291", description: "ضغط حقن الوقود منخفض جداً", severity: "critical", fix: "فحص مضخة الضغط العالي", module: "engine" },
  "P2293": { code: "P2293", description: "عطل في منظم ضغط الوقود - أداء", severity: "high", fix: "فحص منظم ضغط الوقود", module: "engine" },
  "P2297": { code: "P2297", description: "حساس O2 خارج النطاق أثناء التباطؤ - بنك1 حساس1", severity: "medium", fix: "فحص حساس O2", module: "engine" },
  "P2300": { code: "P2300", description: "عطل في دائرة كويل الإشعال رقم 1 - إشارة منخفضة", severity: "high", fix: "فحص كويل رقم 1", module: "engine" },
  "P2301": { code: "P2301", description: "عطل في دائرة كويل الإشعال رقم 1 - إشارة مرتفعة", severity: "high", fix: "استبدال كويل رقم 1", module: "engine" },
  "P2303": { code: "P2303", description: "عطل في دائرة كويل الإشعال رقم 2 - إشارة منخفضة", severity: "high", fix: "فحص كويل رقم 2", module: "engine" },
  "P2304": { code: "P2304", description: "عطل في دائرة كويل الإشعال رقم 2 - إشارة مرتفعة", severity: "high", fix: "استبدال كويل رقم 2", module: "engine" },
  "P2400": { code: "P2400", description: "عطل في مضخة هواء EVAP - أداء", severity: "medium", fix: "فحص مضخة هواء EVAP", module: "engine" },
  "P2401": { code: "P2401", description: "عطل في مضخة هواء EVAP - إشارة منخفضة", severity: "medium", fix: "فحص أسلاك مضخة EVAP", module: "engine" },
  "P2402": { code: "P2402", description: "عطل في مضخة هواء EVAP - إشارة مرتفعة", severity: "medium", fix: "فحص مضخة EVAP", module: "engine" },
  "P2404": { code: "P2404", description: "عطل في نظام EVAP - تسريب مكتشف", severity: "medium", fix: "فحص غطاء الوقود والخراطيم", module: "engine" },
  "P2420": { code: "P2420", description: "عطل في صمام تبديل EVAP - بنك1", severity: "medium", fix: "فحص صمام EVAP", module: "engine" },
  "P2431": { code: "P2431", description: "عطل في مضخة الهواء الثانوية - أداء", severity: "medium", fix: "فحص مضخة الهواء الثانوية", module: "engine" },
  "P2432": { code: "P2432", description: "عطل في مضخة الهواء الثانوية - تدفق", severity: "medium", fix: "فحص صمام الهواء الثانوي", module: "engine" },
  "P2440": { code: "P2440", description: "عطل في صمام الهواء الثانوي - عالق مفتوح بنك1", severity: "medium", fix: "استبدال صمام الهواء الثانوي", module: "engine" },
  "P2441": { code: "P2441", description: "عطل في صمام الهواء الثانوي - عالق مغلق بنك1", severity: "medium", fix: "استبدال صمام الهواء الثانوي", module: "engine" },
  "P2444": { code: "P2444", description: "عطل في مضخة الهواء الثانوية - عالقة ON بنك1", severity: "medium", fix: "فحص ريلاي مضخة الهواء", module: "engine" },
  "P2503": { code: "P2503", description: "عطل في جهد نظام الشحن - منخفض", severity: "high", fix: "فحص الدينمو والبطارية", module: "engine" },
  "P2504": { code: "P2504", description: "عطل في جهد نظام الشحن - مرتفع", severity: "high", fix: "فحص منظم الجهد في الدينمو", module: "engine" },
  "P2610": { code: "P2610", description: "عطل في مؤقت ECM/PCM - أداء", severity: "medium", fix: "إعادة برمجة ECM", module: "engine" },
  "P2626": { code: "P2626", description: "عطل في حساس O2 - تيار ضخ منخفض بنك1 حساس1", severity: "high", fix: "استبدال حساس O2", module: "engine" },
  "P2629": { code: "P2629", description: "عطل في حساس O2 - تيار ضخ مرتفع بنك1 حساس1", severity: "high", fix: "استبدال حساس O2", module: "engine" },
  "P2646": { code: "P2646", description: "عطل في صمام VTEC/VVT - أداء بنك1", severity: "high", fix: "فحص صمام VTEC وزيت المحرك", module: "engine" },
  "P2647": { code: "P2647", description: "عطل في صمام VTEC/VVT - عالق ON بنك1", severity: "high", fix: "فحص صمام VTEC", module: "engine" },
  "P2648": { code: "P2648", description: "عطل في صمام VTEC/VVT - إشارة منخفضة بنك1", severity: "high", fix: "فحص أسلاك صمام VTEC", module: "engine" },
  "P2649": { code: "P2649", description: "عطل في صمام VTEC/VVT - إشارة مرتفعة بنك1", severity: "high", fix: "فحص أسلاك صمام VTEC", module: "engine" },
  "P2714": { code: "P2714", description: "عطل في صمام ضغط القير D - أداء/عالق OFF", severity: "high", fix: "فحص صمام ضغط القير", module: "transmission" },
  "P2715": { code: "P2715", description: "عطل في صمام ضغط القير D - عالق ON", severity: "high", fix: "فحص صمام ضغط القير", module: "transmission" },
  "P2716": { code: "P2716", description: "عطل في صمام ضغط القير D - كهربائي", severity: "high", fix: "فحص أسلاك صمام القير", module: "transmission" },
  "P2757": { code: "P2757", description: "عطل في صمام TCC - أداء/عالق OFF", severity: "high", fix: "فحص صمام TCC وزيت القير", module: "transmission" },
  "P2758": { code: "P2758", description: "عطل في صمام TCC - عالق ON", severity: "high", fix: "فحص صمام TCC", module: "transmission" },
  "P2759": { code: "P2759", description: "عطل في صمام TCC - كهربائي", severity: "high", fix: "فحص أسلاك صمام TCC", module: "transmission" },
  "P2761": { code: "P2761", description: "عطل في صمام TCC - دائرة مفتوحة", severity: "high", fix: "فحص أسلاك وموصلات TCC", module: "transmission" },
  "P2762": { code: "P2762", description: "عطل في صمام TCC - عالق ON", severity: "high", fix: "استبدال صمام TCC", module: "transmission" },
  "P2763": { code: "P2763", description: "عطل في صمام TCC - إشارة مرتفعة", severity: "high", fix: "فحص دائرة TCC", module: "transmission" },
  "P2764": { code: "P2764", description: "عطل في صمام TCC - إشارة منخفضة", severity: "high", fix: "فحص دائرة TCC", module: "transmission" },
  "P2769": { code: "P2769", description: "عطل في صمام محول العزم - إشارة منخفضة", severity: "high", fix: "فحص صمام محول العزم", module: "transmission" },
  "P2770": { code: "P2770", description: "عطل في صمام محول العزم - إشارة مرتفعة", severity: "high", fix: "فحص صمام محول العزم", module: "transmission" },
  // ═══ P3xxx - أكواد إضافية ═══
  "P3400": { code: "P3400", description: "عطل في نظام إدارة الأسطوانات - بنك1", severity: "high", fix: "فحص نظام VCM/DOD", module: "engine" },
  "P3401": { code: "P3401", description: "عطل في صمام إلغاء أسطوانة 1", severity: "high", fix: "فحص صمام إلغاء الأسطوانة", module: "engine" },
  "P3425": { code: "P3425", description: "عطل في صمام إلغاء أسطوانة 4", severity: "high", fix: "فحص صمام إلغاء الأسطوانة", module: "engine" },
  "P3441": { code: "P3441", description: "عطل في صمام إلغاء أسطوانة 7", severity: "high", fix: "فحص صمام إلغاء الأسطوانة", module: "engine" },
  "P3449": { code: "P3449", description: "عطل في صمام إلغاء أسطوانة 8", severity: "high", fix: "فحص صمام إلغاء الأسطوانة", module: "engine" },
  "P3497": { code: "P3497", description: "عطل في نظام إدارة الأسطوانات - بنك2", severity: "high", fix: "فحص نظام VCM/DOD بنك2", module: "engine" },
  // ═══ B1xxx - أكواد هيكل المصنّع ═══
  "B1200": { code: "B1200", description: "عطل في دائرة مناخ السيارة - حساس درجة الحرارة", severity: "medium", fix: "فحص حساس حرارة المقصورة", module: "body" },
  "B1201": { code: "B1201", description: "عطل في محرك باب المزج - المكيف", severity: "medium", fix: "فحص محرك باب المزج", module: "body" },
  "B1202": { code: "B1202", description: "عطل في محرك توزيع الهواء - المكيف", severity: "medium", fix: "فحص محرك التوزيع", module: "body" },
  "B1210": { code: "B1210", description: "عطل في حساس ضوء الشمس", severity: "low", fix: "فحص حساس ضوء الشمس", module: "body" },
  "B1213": { code: "B1213", description: "عطل في حساس درجة حرارة الهواء الخارجي", severity: "low", fix: "فحص حساس الحرارة الخارجية", module: "body" },
  "B1231": { code: "B1231", description: "عطل في دائرة قفل الباب الأمامي الأيسر", severity: "medium", fix: "فحص محرك القفل والأسلاك", module: "body" },
  "B1232": { code: "B1232", description: "عطل في دائرة قفل الباب الأمامي الأيمن", severity: "medium", fix: "فحص محرك القفل والأسلاك", module: "body" },
  "B1233": { code: "B1233", description: "عطل في دائرة قفل الباب الخلفي الأيسر", severity: "medium", fix: "فحص محرك القفل والأسلاك", module: "body" },
  "B1234": { code: "B1234", description: "عطل في دائرة قفل الباب الخلفي الأيمن", severity: "medium", fix: "فحص محرك القفل والأسلاك", module: "body" },
  "B1240": { code: "B1240", description: "عطل في نظام النوافذ الكهربائية - الأمامية اليسرى", severity: "medium", fix: "فحص محرك النافذة والمفتاح", module: "body" },
  "B1241": { code: "B1241", description: "عطل في نظام النوافذ الكهربائية - الأمامية اليمنى", severity: "medium", fix: "فحص محرك النافذة والمفتاح", module: "body" },
  "B1242": { code: "B1242", description: "عطل في نظام النوافذ الكهربائية - الخلفية اليسرى", severity: "medium", fix: "فحص محرك النافذة والمفتاح", module: "body" },
  "B1243": { code: "B1243", description: "عطل في نظام النوافذ الكهربائية - الخلفية اليمنى", severity: "medium", fix: "فحص محرك النافذة والمفتاح", module: "body" },
  "B1250": { code: "B1250", description: "عطل في نظام المرايا الكهربائية - اليسرى", severity: "low", fix: "فحص محرك المرآة", module: "body" },
  "B1251": { code: "B1251", description: "عطل في نظام المرايا الكهربائية - اليمنى", severity: "low", fix: "فحص محرك المرآة", module: "body" },
  "B1317": { code: "B1317", description: "جهد البطارية مرتفع - وحدة BCM", severity: "high", fix: "فحص الدينمو ومنظم الجهد", module: "body" },
  "B1318": { code: "B1318", description: "جهد البطارية منخفض - وحدة BCM", severity: "high", fix: "فحص البطارية والشحن", module: "body" },
  "B1325": { code: "B1325", description: "عطل في نظام الإضاءة التلقائية", severity: "medium", fix: "فحص حساس الإضاءة", module: "body" },
  "B1342": { code: "B1342", description: "عطل في وحدة BCM - خطأ داخلي", severity: "high", fix: "إعادة برمجة أو استبدال BCM", module: "body" },
  "B1352": { code: "B1352", description: "عطل في نظام منع السرقة - مفتاح غير معرّف", severity: "high", fix: "إعادة برمجة المفتاح", module: "body" },
  "B1359": { code: "B1359", description: "عطل في نظام منع السرقة - خطأ اتصال", severity: "high", fix: "فحص هوائي المفتاح", module: "body" },
  "B1400": { code: "B1400", description: "عطل في حساس المطر", severity: "low", fix: "فحص حساس المطر", module: "body" },
  "B1410": { code: "B1410", description: "عطل في نظام المساحات التلقائية", severity: "medium", fix: "فحص محرك المساحات", module: "body" },
  "B1450": { code: "B1450", description: "عطل في نظام فتح السقف الكهربائي", severity: "medium", fix: "فحص محرك السقف", module: "body" },
  "B1462": { code: "B1462", description: "عطل في حساس ضغط المكيف", severity: "medium", fix: "فحص حساس ضغط الفريون", module: "body" },
  "B1470": { code: "B1470", description: "عطل في كمبروسر المكيف - لا يعمل", severity: "high", fix: "فحص كلتش وكمبروسر المكيف", module: "body" },
  "B1480": { code: "B1480", description: "عطل في محرك المروحة الداخلية", severity: "medium", fix: "فحص مقاومة ومحرك المروحة", module: "body" },
  "B1500": { code: "B1500", description: "عطل في نظام الصوت - وحدة الرأس", severity: "low", fix: "فحص وحدة الصوت", module: "body" },
  "B1510": { code: "B1510", description: "عطل في نظام الصوت - مكبر الصوت", severity: "low", fix: "فحص مكبر الصوت والأسلاك", module: "body" },
  "B1550": { code: "B1550", description: "عطل في شاشة المعلومات", severity: "medium", fix: "فحص شاشة المعلومات", module: "body" },
  "B1600": { code: "B1600", description: "عطل في نظام TPMS - حساس ضغط الإطار", severity: "medium", fix: "إعادة تعلم حساسات TPMS", module: "body" },
  "B1601": { code: "B1601", description: "عطل في حساس TPMS - الإطار الأمامي الأيسر", severity: "medium", fix: "استبدال حساس TPMS", module: "body" },
  "B1602": { code: "B1602", description: "عطل في حساس TPMS - الإطار الأمامي الأيمن", severity: "medium", fix: "استبدال حساس TPMS", module: "body" },
  "B1603": { code: "B1603", description: "عطل في حساس TPMS - الإطار الخلفي الأيسر", severity: "medium", fix: "استبدال حساس TPMS", module: "body" },
  "B1604": { code: "B1604", description: "عطل في حساس TPMS - الإطار الخلفي الأيمن", severity: "medium", fix: "استبدال حساس TPMS", module: "body" },
  "B1620": { code: "B1620", description: "عطل في نظام الكاميرا الخلفية", severity: "medium", fix: "فحص الكاميرا والأسلاك", module: "body" },
  "B1650": { code: "B1650", description: "عطل في نظام المقاعد الكهربائية", severity: "low", fix: "فحص محرك المقعد", module: "body" },
  "B1660": { code: "B1660", description: "عطل في نظام تسخين المقاعد", severity: "low", fix: "فحص عنصر التسخين", module: "body" },
  "B1676": { code: "B1676", description: "عطل في البطارية - جهد منخفض أثناء التشغيل", severity: "high", fix: "فحص البطارية والمارش", module: "body" },
  "B1681": { code: "B1681", description: "عطل في نظام PATS/NATS - مفتاح غير صالح", severity: "high", fix: "إعادة برمجة المفتاح", module: "body" },
  "B1700": { code: "B1700", description: "عطل في نظام الوسائد الهوائية الجانبية", severity: "critical", fix: "فحص نظام SRS فوراً", module: "body" },
  "B1800": { code: "B1800", description: "عطل في نظام حزام الأمان الأمامي", severity: "high", fix: "فحص شداد حزام الأمان", module: "body" },
  "B1810": { code: "B1810", description: "عطل في حساس وزن الراكب الأمامي", severity: "high", fix: "فحص حساس المقعد", module: "body" },
  "B1900": { code: "B1900", description: "عطل في وحدة التحكم بالمقود - أزرار", severity: "low", fix: "فحص أزرار المقود", module: "body" },
  // ═══ C1xxx - أكواد شاسيه المصنّع ═══
  "C1095": { code: "C1095", description: "عطل في حساس سرعة العجلة الأمامية اليسرى - ABS", severity: "high", fix: "فحص حساس ABS الأمامي الأيسر", module: "abs" },
  "C1096": { code: "C1096", description: "عطل في حساس سرعة العجلة الأمامية اليمنى - ABS", severity: "high", fix: "فحص حساس ABS الأمامي الأيمن", module: "abs" },
  "C1097": { code: "C1097", description: "عطل في حساس سرعة العجلة الخلفية اليسرى - ABS", severity: "high", fix: "فحص حساس ABS الخلفي الأيسر", module: "abs" },
  "C1098": { code: "C1098", description: "عطل في حساس سرعة العجلة الخلفية اليمنى - ABS", severity: "high", fix: "فحص حساس ABS الخلفي الأيمن", module: "abs" },
  "C1100": { code: "C1100", description: "عطل في مضخة ABS الهيدروليكية", severity: "critical", fix: "فحص مضخة ABS", module: "abs" },
  "C1101": { code: "C1101", description: "عطل في صمام ABS - الأمامي الأيسر", severity: "high", fix: "فحص صمام ABS", module: "abs" },
  "C1102": { code: "C1102", description: "عطل في صمام ABS - الأمامي الأيمن", severity: "high", fix: "فحص صمام ABS", module: "abs" },
  "C1103": { code: "C1103", description: "عطل في صمام ABS - الخلفي الأيسر", severity: "high", fix: "فحص صمام ABS", module: "abs" },
  "C1104": { code: "C1104", description: "عطل في صمام ABS - الخلفي الأيمن", severity: "high", fix: "فحص صمام ABS", module: "abs" },
  "C1130": { code: "C1130", description: "عطل في حساس زاوية المقود - نظام ESP", severity: "high", fix: "معايرة حساس زاوية المقود", module: "abs" },
  "C1131": { code: "C1131", description: "عطل في حساس التسارع الجانبي - ESP", severity: "high", fix: "فحص حساس التسارع", module: "abs" },
  "C1132": { code: "C1132", description: "عطل في حساس معدل الدوران Yaw - ESP", severity: "high", fix: "فحص حساس Yaw", module: "abs" },
  "C1140": { code: "C1140", description: "عطل في نظام ESP - تم تعطيله", severity: "high", fix: "فحص نظام ESP وحساساته", module: "abs" },
  "C1145": { code: "C1145", description: "عطل في حساس ضغط الفرامل", severity: "high", fix: "فحص حساس ضغط الفرامل", module: "abs" },
  "C1185": { code: "C1185", description: "عطل في مضخة ABS - محرك كهربائي", severity: "critical", fix: "استبدال مضخة ABS", module: "abs" },
  "C1200": { code: "C1200", description: "عطل في نظام التوجيه الكهربائي EPS - عزم", severity: "high", fix: "فحص محرك EPS", module: "abs" },
  "C1201": { code: "C1201", description: "عطل في نظام EPS - حساس العزم", severity: "high", fix: "فحص حساس عزم المقود", module: "abs" },
  "C1210": { code: "C1210", description: "عطل في نظام EPS - درجة حرارة مرتفعة", severity: "high", fix: "ترك النظام يبرد وفحص الحمل", module: "abs" },
  "C1220": { code: "C1220", description: "عطل في نظام EPS - جهد منخفض", severity: "high", fix: "فحص البطارية والشحن", module: "abs" },
  "C1230": { code: "C1230", description: "عطل في نظام EPS - وحدة التحكم", severity: "high", fix: "إعادة برمجة أو استبدال وحدة EPS", module: "abs" },
  "C1241": { code: "C1241", description: "عطل في جهد مضخة ABS - منخفض", severity: "high", fix: "فحص البطارية وأسلاك ABS", module: "abs" },
  "C1242": { code: "C1242", description: "عطل في جهد مضخة ABS - مرتفع", severity: "high", fix: "فحص منظم الجهد", module: "abs" },
  "C1250": { code: "C1250", description: "عطل في نظام الفرامل الإلكترونية EPB", severity: "high", fix: "فحص نظام EPB", module: "abs" },
  "C1251": { code: "C1251", description: "عطل في محرك EPB - الأيسر", severity: "high", fix: "فحص محرك الفرامل الإلكترونية", module: "abs" },
  "C1252": { code: "C1252", description: "عطل في محرك EPB - الأيمن", severity: "high", fix: "فحص محرك الفرامل الإلكترونية", module: "abs" },
  "C1260": { code: "C1260", description: "عطل في نظام التحكم بالجر TCS", severity: "high", fix: "فحص نظام TCS", module: "abs" },
  "C1270": { code: "C1270", description: "عطل في حساس ضغط الفرامل الرئيسي", severity: "high", fix: "فحص حساس الضغط", module: "abs" },
  "C1280": { code: "C1280", description: "عطل في نظام توزيع قوة الفرملة EBD", severity: "critical", fix: "فحص نظام EBD فوراً", module: "abs" },
  "C1300": { code: "C1300", description: "عطل في نظام التعليق الهوائي - ضاغط", severity: "high", fix: "فحص ضاغط التعليق الهوائي", module: "abs" },
  "C1301": { code: "C1301", description: "عطل في التعليق الهوائي - حساس ارتفاع أمامي أيسر", severity: "high", fix: "فحص حساس الارتفاع", module: "abs" },
  "C1302": { code: "C1302", description: "عطل في التعليق الهوائي - حساس ارتفاع أمامي أيمن", severity: "high", fix: "فحص حساس الارتفاع", module: "abs" },
  "C1303": { code: "C1303", description: "عطل في التعليق الهوائي - حساس ارتفاع خلفي أيسر", severity: "high", fix: "فحص حساس الارتفاع", module: "abs" },
  "C1304": { code: "C1304", description: "عطل في التعليق الهوائي - حساس ارتفاع خلفي أيمن", severity: "high", fix: "فحص حساس الارتفاع", module: "abs" },
  "C1310": { code: "C1310", description: "عطل في التعليق الهوائي - تسريب هواء", severity: "high", fix: "فحص وسائد الهواء والأنابيب", module: "abs" },
  "C1400": { code: "C1400", description: "عطل في نظام الدفع الرباعي 4WD", severity: "high", fix: "فحص نظام الدفع الرباعي", module: "abs" },
  "C1401": { code: "C1401", description: "عطل في محرك نقل الدفع الرباعي", severity: "high", fix: "فحص محرك نقل الحركة", module: "abs" },
  "C1500": { code: "C1500", description: "عطل في نظام مساعد الفرملة BA", severity: "high", fix: "فحص نظام BA", module: "abs" },
  "C1510": { code: "C1510", description: "عطل في نظام مساعد بدء الانطلاق HSA", severity: "medium", fix: "فحص نظام HSA", module: "abs" },
  "C1520": { code: "C1520", description: "عطل في نظام التحكم بالثبات على المنحدرات HDC", severity: "medium", fix: "فحص نظام HDC", module: "abs" },
  "C1600": { code: "C1600", description: "عطل في وحدة التحكم بالفرامل ABS/ESP", severity: "critical", fix: "فحص وإعادة برمجة وحدة ABS", module: "abs" },
  "C1700": { code: "C1700", description: "عطل في نظام مساعد الركن - حساس أمامي", severity: "low", fix: "فحص حساسات الركن الأمامية", module: "abs" },
  "C1701": { code: "C1701", description: "عطل في نظام مساعد الركن - حساس خلفي", severity: "low", fix: "فحص حساسات الركن الخلفية", module: "abs" },
  "C1710": { code: "C1710", description: "عطل في نظام الرؤية المحيطية 360", severity: "medium", fix: "فحص الكاميرات", module: "abs" },
};
