/**
 * OBD2 DTC Database — P0xxx Codes (SAE Standard)
 * أكواد P0xxx الكاملة — المحرك، الوقود، الهواء، الإشعال، الانبعاثات
 * ~400 كود بالعربي الكامل
 */
import type { DTCInfo } from "./obdDtcDatabase";

export const P0_DTC: Record<string, DTCInfo> = {

  // ══════════════════════════════════════════════
  // P0001–P0099 — نظام التحكم بالوقود والهواء
  // ══════════════════════════════════════════════
  "P0001": { code:"P0001", description:"Fuel Volume Regulator Control Circuit Open", descriptionAr:"دائرة منظم حجم الوقود مفتوحة", system:"engine", subsystem:"Fuel System", subsystemAr:"نظام الوقود", severity:"high", causes:["Fuel pressure regulator fault","Wiring open circuit","PCM fault"], causesAr:["عطل منظم ضغط الوقود","دائرة مفتوحة في الأسلاك","عطل PCM"], solution:"Check fuel pressure regulator wiring and replace if needed", solutionAr:"فحص أسلاك منظم ضغط الوقود واستبداله إذا لزم", relatedSensors:["FRP Sensor"], affectedComponents:["Fuel Pressure Regulator"], affectedComponentsAr:["منظم ضغط الوقود"], safeToRide:false, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },
  "P0002": { code:"P0002", description:"Fuel Volume Regulator Control Circuit Range/Performance", descriptionAr:"أداء دائرة منظم حجم الوقود خارج النطاق", system:"engine", subsystem:"Fuel System", subsystemAr:"نظام الوقود", severity:"high", causes:["Regulator stuck","Fuel contamination","PCM fault"], causesAr:["منظم عالق","تلوث الوقود","عطل PCM"], solution:"Test regulator operation, check fuel quality", solutionAr:"اختبار عمل المنظم وفحص جودة الوقود", relatedSensors:["FRP Sensor"], affectedComponents:["Fuel Pressure Regulator"], affectedComponentsAr:["منظم ضغط الوقود"], safeToRide:false, estimatedRepairCost:{min:200,max:1000,currency:"SAR"} },
  "P0003": { code:"P0003", description:"Fuel Volume Regulator Control Circuit Low", descriptionAr:"جهد منخفض في دائرة منظم حجم الوقود", system:"engine", subsystem:"Fuel System", subsystemAr:"نظام الوقود", severity:"high", causes:["Short to ground","Regulator fault","PCM fault"], causesAr:["قصر أرضي","عطل المنظم","عطل PCM"], solution:"Check for short to ground in regulator circuit", solutionAr:"فحص القصر الأرضي في دائرة المنظم", relatedSensors:["FRP Sensor"], affectedComponents:["Fuel Pressure Regulator"], affectedComponentsAr:["منظم ضغط الوقود"], safeToRide:false, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },
  "P0004": { code:"P0004", description:"Fuel Volume Regulator Control Circuit High", descriptionAr:"جهد مرتفع في دائرة منظم حجم الوقود", system:"engine", subsystem:"Fuel System", subsystemAr:"نظام الوقود", severity:"high", causes:["Short to power","Regulator fault","PCM fault"], causesAr:["قصر للطاقة","عطل المنظم","عطل PCM"], solution:"Check for short to power in regulator circuit", solutionAr:"فحص القصر للطاقة في دائرة المنظم", relatedSensors:["FRP Sensor"], affectedComponents:["Fuel Pressure Regulator"], affectedComponentsAr:["منظم ضغط الوقود"], safeToRide:false, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },

  "P0010": { code:"P0010", description:"Intake Camshaft Position Actuator Circuit Bank 1", descriptionAr:"عطل في دائرة محرك موضع الكامشافت الأمامي - البنك 1", system:"engine", subsystem:"VVT System", subsystemAr:"نظام توقيت الصمامات", severity:"high", causes:["VVT solenoid fault","Oil pressure low","Sludge in oil passages","PCM fault"], causesAr:["عطل صمام VVT","ضغط زيت منخفض","رواسب في ممرات الزيت","عطل PCM"], solution:"Check VVT solenoid, oil level and quality, clean oil passages", solutionAr:"فحص صمام VVT ومستوى الزيت وتنظيف ممرات الزيت", relatedSensors:["CMP Sensor","CKP Sensor"], affectedComponents:["VVT Solenoid","Camshaft Phaser"], affectedComponentsAr:["صمام VVT","محرك الكامشافت"], safeToRide:false, estimatedRepairCost:{min:300,max:1500,currency:"SAR"} },
  "P0011": { code:"P0011", description:"Intake Camshaft Position Over-Advanced Bank 1", descriptionAr:"توقيت الكامشافت الأمامي متقدم أكثر من اللازم - البنك 1", system:"engine", subsystem:"VVT System", subsystemAr:"نظام توقيت الصمامات", severity:"high", causes:["VVT solenoid stuck open","Low oil pressure","Wrong oil viscosity","Worn timing chain"], causesAr:["صمام VVT عالق مفتوح","ضغط زيت منخفض","لزوجة زيت خاطئة","سلسلة توقيت متآكلة"], solution:"Check oil level/quality, test VVT solenoid, inspect timing chain", solutionAr:"فحص مستوى وجودة الزيت، اختبار صمام VVT، فحص سلسلة التوقيت", relatedSensors:["CMP Sensor","CKP Sensor"], affectedComponents:["VVT Solenoid","Timing Chain"], affectedComponentsAr:["صمام VVT","سلسلة التوقيت"], safeToRide:false, estimatedRepairCost:{min:300,max:2000,currency:"SAR"} },
  "P0012": { code:"P0012", description:"Intake Camshaft Position Over-Retarded Bank 1", descriptionAr:"توقيت الكامشافت الأمامي متأخر أكثر من اللازم - البنك 1", system:"engine", subsystem:"VVT System", subsystemAr:"نظام توقيت الصمامات", severity:"high", causes:["VVT solenoid stuck closed","Camshaft phaser worn","Oil sludge"], causesAr:["صمام VVT عالق مغلق","محرك الكامشافت متآكل","رواسب الزيت"], solution:"Clean VVT solenoid, check oil passages, replace phaser if needed", solutionAr:"تنظيف صمام VVT وفحص ممرات الزيت واستبدال المحرك إذا لزم", relatedSensors:["CMP Sensor"], affectedComponents:["VVT Solenoid","Camshaft Phaser"], affectedComponentsAr:["صمام VVT","محرك الكامشافت"], safeToRide:false, estimatedRepairCost:{min:300,max:2000,currency:"SAR"} },
  "P0013": { code:"P0013", description:"Exhaust Camshaft Position Actuator Circuit Bank 1", descriptionAr:"عطل في دائرة محرك موضع الكامشافت الخلفي - البنك 1", system:"engine", subsystem:"VVT System", subsystemAr:"نظام توقيت الصمامات", severity:"high", causes:["Exhaust VVT solenoid fault","Wiring issue","PCM fault"], causesAr:["عطل صمام VVT العادم","مشكلة أسلاك","عطل PCM"], solution:"Test exhaust VVT solenoid and wiring", solutionAr:"اختبار صمام VVT العادم والأسلاك", relatedSensors:["CMP Sensor"], affectedComponents:["Exhaust VVT Solenoid"], affectedComponentsAr:["صمام VVT العادم"], safeToRide:false, estimatedRepairCost:{min:300,max:1500,currency:"SAR"} },
  "P0014": { code:"P0014", description:"Exhaust Camshaft Position Over-Advanced Bank 1", descriptionAr:"توقيت الكامشافت الخلفي متقدم أكثر من اللازم - البنك 1", system:"engine", subsystem:"VVT System", subsystemAr:"نظام توقيت الصمامات", severity:"high", causes:["Exhaust VVT solenoid stuck","Low oil pressure","Wrong oil"], causesAr:["صمام VVT العادم عالق","ضغط زيت منخفض","زيت خاطئ"], solution:"Check oil, test exhaust VVT solenoid", solutionAr:"فحص الزيت واختبار صمام VVT العادم", relatedSensors:["CMP Sensor"], affectedComponents:["Exhaust VVT Solenoid"], affectedComponentsAr:["صمام VVT العادم"], safeToRide:false, estimatedRepairCost:{min:300,max:1500,currency:"SAR"} },
  "P0015": { code:"P0015", description:"Exhaust Camshaft Position Over-Retarded Bank 1", descriptionAr:"توقيت الكامشافت الخلفي متأخر أكثر من اللازم - البنك 1", system:"engine", subsystem:"VVT System", subsystemAr:"نظام توقيت الصمامات", severity:"high", causes:["Exhaust VVT solenoid stuck closed","Oil sludge"], causesAr:["صمام VVT العادم عالق مغلق","رواسب الزيت"], solution:"Clean VVT solenoid, change oil", solutionAr:"تنظيف صمام VVT وتغيير الزيت", relatedSensors:["CMP Sensor"], affectedComponents:["Exhaust VVT Solenoid"], affectedComponentsAr:["صمام VVT العادم"], safeToRide:false, estimatedRepairCost:{min:300,max:1500,currency:"SAR"} },
  "P0016": { code:"P0016", description:"Crankshaft/Camshaft Position Correlation Bank 1 Intake", descriptionAr:"عدم تزامن الكرنك مع الكامشافت الأمامي - البنك 1", system:"engine", subsystem:"Timing", subsystemAr:"نظام التوقيت", severity:"critical", causes:["Timing chain stretched","VVT phaser worn","Timing marks misaligned"], causesAr:["سلسلة توقيت متمددة","محرك VVT متآكل","علامات التوقيت غير متوافقة"], solution:"Inspect timing chain and replace if stretched, check VVT phaser", solutionAr:"فحص سلسلة التوقيت واستبدالها إذا تمددت وفحص محرك VVT", relatedSensors:["CKP Sensor","CMP Sensor"], affectedComponents:["Timing Chain","VVT Phaser"], affectedComponentsAr:["سلسلة التوقيت","محرك VVT"], safeToRide:false, estimatedRepairCost:{min:1000,max:5000,currency:"SAR"} },
  "P0017": { code:"P0017", description:"Crankshaft/Camshaft Position Correlation Bank 1 Exhaust", descriptionAr:"عدم تزامن الكرنك مع الكامشافت الخلفي - البنك 1", system:"engine", subsystem:"Timing", subsystemAr:"نظام التوقيت", severity:"critical", causes:["Timing chain stretched","Exhaust VVT phaser worn"], causesAr:["سلسلة توقيت متمددة","محرك VVT العادم متآكل"], solution:"Inspect timing chain and exhaust VVT phaser", solutionAr:"فحص سلسلة التوقيت ومحرك VVT العادم", relatedSensors:["CKP Sensor","CMP Sensor"], affectedComponents:["Timing Chain"], affectedComponentsAr:["سلسلة التوقيت"], safeToRide:false, estimatedRepairCost:{min:1000,max:5000,currency:"SAR"} },
  "P0018": { code:"P0018", description:"Crankshaft/Camshaft Position Correlation Bank 2 Intake", descriptionAr:"عدم تزامن الكرنك مع الكامشافت الأمامي - البنك 2", system:"engine", subsystem:"Timing", subsystemAr:"نظام التوقيت", severity:"critical", causes:["Timing chain stretched","VVT phaser worn Bank 2"], causesAr:["سلسلة توقيت متمددة","محرك VVT متآكل البنك 2"], solution:"Inspect timing chain Bank 2", solutionAr:"فحص سلسلة التوقيت للبنك 2", relatedSensors:["CKP Sensor","CMP Sensor B2"], affectedComponents:["Timing Chain"], affectedComponentsAr:["سلسلة التوقيت"], safeToRide:false, estimatedRepairCost:{min:1000,max:5000,currency:"SAR"} },
  "P0019": { code:"P0019", description:"Crankshaft/Camshaft Position Correlation Bank 2 Exhaust", descriptionAr:"عدم تزامن الكرنك مع الكامشافت الخلفي - البنك 2", system:"engine", subsystem:"Timing", subsystemAr:"نظام التوقيت", severity:"critical", causes:["Timing chain stretched B2","Exhaust VVT phaser worn B2"], causesAr:["سلسلة توقيت متمددة البنك 2","محرك VVT العادم متآكل البنك 2"], solution:"Inspect timing chain and exhaust VVT phaser Bank 2", solutionAr:"فحص سلسلة التوقيت ومحرك VVT العادم للبنك 2", relatedSensors:["CKP Sensor","CMP Sensor B2"], affectedComponents:["Timing Chain B2"], affectedComponentsAr:["سلسلة التوقيت البنك 2"], safeToRide:false, estimatedRepairCost:{min:1000,max:5000,currency:"SAR"} },
  "P0020": { code:"P0020", description:"Intake Camshaft Position Actuator Circuit Bank 2", descriptionAr:"عطل في دائرة محرك موضع الكامشافت الأمامي - البنك 2", system:"engine", subsystem:"VVT System", subsystemAr:"نظام توقيت الصمامات", severity:"high", causes:["VVT solenoid B2 fault","Wiring issue"], causesAr:["عطل صمام VVT البنك 2","مشكلة أسلاك"], solution:"Test VVT solenoid Bank 2", solutionAr:"اختبار صمام VVT للبنك 2", relatedSensors:["CMP Sensor B2"], affectedComponents:["VVT Solenoid B2"], affectedComponentsAr:["صمام VVT البنك 2"], safeToRide:false, estimatedRepairCost:{min:300,max:1500,currency:"SAR"} },

  // ══════════════════════════════════════════════
  // P0030–P0065 — حساسات الأكسجين O2
  // ══════════════════════════════════════════════
  "P0030": { code:"P0030", description:"O2 Sensor Heater Circuit Bank 1 Sensor 1", descriptionAr:"عطل في دائرة سخان حساس الأكسجين B1S1", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"medium", causes:["Heater element burned","Blown fuse","Wiring fault"], causesAr:["عنصر السخان محترق","فيوز محترق","عطل أسلاك"], solution:"Check heater fuse, test heater resistance (should be 3-30 ohms)", solutionAr:"فحص فيوز السخان وقياس مقاومة السخان (3-30 أوم)", relatedSensors:["O2 Sensor B1S1"], affectedComponents:["O2 Sensor Heater"], affectedComponentsAr:["سخان حساس الأكسجين"], safeToRide:true, estimatedRepairCost:{min:150,max:600,currency:"SAR"} },
  "P0031": { code:"P0031", description:"O2 Sensor Heater Circuit Low Bank 1 Sensor 1", descriptionAr:"جهد منخفض في سخان حساس الأكسجين B1S1", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"medium", causes:["Short to ground","Heater fault"], causesAr:["قصر أرضي","عطل السخان"], solution:"Check for short to ground in heater circuit", solutionAr:"فحص القصر الأرضي في دائرة السخان", relatedSensors:["O2 Sensor B1S1"], affectedComponents:["O2 Sensor"], affectedComponentsAr:["حساس الأكسجين"], safeToRide:true, estimatedRepairCost:{min:150,max:600,currency:"SAR"} },
  "P0032": { code:"P0032", description:"O2 Sensor Heater Circuit High Bank 1 Sensor 1", descriptionAr:"جهد مرتفع في سخان حساس الأكسجين B1S1", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"medium", causes:["Short to power","Heater fault"], causesAr:["قصر للطاقة","عطل السخان"], solution:"Check for short to power in heater circuit", solutionAr:"فحص القصر للطاقة في دائرة السخان", relatedSensors:["O2 Sensor B1S1"], affectedComponents:["O2 Sensor"], affectedComponentsAr:["حساس الأكسجين"], safeToRide:true, estimatedRepairCost:{min:150,max:600,currency:"SAR"} },
  "P0036": { code:"P0036", description:"O2 Sensor Heater Circuit Bank 1 Sensor 2", descriptionAr:"عطل في دائرة سخان حساس الأكسجين B1S2", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"low", causes:["Heater burned","Wiring fault"], causesAr:["سخان محترق","عطل أسلاك"], solution:"Replace rear O2 sensor or check wiring", solutionAr:"استبدال حساس الأكسجين الخلفي أو فحص الأسلاك", relatedSensors:["O2 Sensor B1S2"], affectedComponents:["O2 Sensor B1S2"], affectedComponentsAr:["حساس الأكسجين الخلفي B1"], safeToRide:true, estimatedRepairCost:{min:150,max:600,currency:"SAR"} },
  "P0037": { code:"P0037", description:"O2 Sensor Heater Circuit Low Bank 1 Sensor 2", descriptionAr:"جهد منخفض في سخان حساس الأكسجين B1S2", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"low", causes:["Short to ground","Heater fault"], causesAr:["قصر أرضي","عطل السخان"], solution:"Check heater circuit for short", solutionAr:"فحص دائرة السخان للقصر", relatedSensors:["O2 Sensor B1S2"], affectedComponents:["O2 Sensor B1S2"], affectedComponentsAr:["حساس الأكسجين الخلفي B1"], safeToRide:true, estimatedRepairCost:{min:150,max:600,currency:"SAR"} },
  "P0038": { code:"P0038", description:"O2 Sensor Heater Circuit High Bank 1 Sensor 2", descriptionAr:"جهد مرتفع في سخان حساس الأكسجين B1S2", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"low", causes:["Short to power"], causesAr:["قصر للطاقة"], solution:"Check heater circuit for short to power", solutionAr:"فحص دائرة السخان للقصر للطاقة", relatedSensors:["O2 Sensor B1S2"], affectedComponents:["O2 Sensor B1S2"], affectedComponentsAr:["حساس الأكسجين الخلفي B1"], safeToRide:true, estimatedRepairCost:{min:150,max:600,currency:"SAR"} },
  "P0042": { code:"P0042", description:"O2 Sensor Heater Circuit Bank 1 Sensor 3", descriptionAr:"عطل في دائرة سخان حساس الأكسجين B1S3", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"low", causes:["Heater fault","Wiring issue"], causesAr:["عطل السخان","مشكلة أسلاك"], solution:"Check O2 sensor 3 heater circuit", solutionAr:"فحص دائرة سخان حساس الأكسجين 3", relatedSensors:["O2 Sensor B1S3"], affectedComponents:["O2 Sensor B1S3"], affectedComponentsAr:["حساس الأكسجين B1S3"], safeToRide:true, estimatedRepairCost:{min:150,max:600,currency:"SAR"} },
  "P0050": { code:"P0050", description:"O2 Sensor Heater Circuit Bank 2 Sensor 1", descriptionAr:"عطل في دائرة سخان حساس الأكسجين B2S1", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"medium", causes:["Heater burned","Fuse blown","Wiring fault"], causesAr:["سخان محترق","فيوز محترق","عطل أسلاك"], solution:"Check heater fuse and O2 sensor B2S1", solutionAr:"فحص فيوز السخان وحساس الأكسجين B2S1", relatedSensors:["O2 Sensor B2S1"], affectedComponents:["O2 Sensor B2S1"], affectedComponentsAr:["حساس الأكسجين الأمامي B2"], safeToRide:true, estimatedRepairCost:{min:150,max:600,currency:"SAR"} },
  "P0051": { code:"P0051", description:"O2 Sensor Heater Circuit Low Bank 2 Sensor 1", descriptionAr:"جهد منخفض في سخان حساس الأكسجين B2S1", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"medium", causes:["Short to ground B2S1"], causesAr:["قصر أرضي B2S1"], solution:"Check heater circuit B2S1 for short to ground", solutionAr:"فحص دائرة السخان B2S1 للقصر الأرضي", relatedSensors:["O2 Sensor B2S1"], affectedComponents:["O2 Sensor B2S1"], affectedComponentsAr:["حساس الأكسجين الأمامي B2"], safeToRide:true, estimatedRepairCost:{min:150,max:600,currency:"SAR"} },
  "P0052": { code:"P0052", description:"O2 Sensor Heater Circuit High Bank 2 Sensor 1", descriptionAr:"جهد مرتفع في سخان حساس الأكسجين B2S1", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"medium", causes:["Short to power B2S1"], causesAr:["قصر للطاقة B2S1"], solution:"Check heater circuit B2S1 for short to power", solutionAr:"فحص دائرة السخان B2S1 للقصر للطاقة", relatedSensors:["O2 Sensor B2S1"], affectedComponents:["O2 Sensor B2S1"], affectedComponentsAr:["حساس الأكسجين الأمامي B2"], safeToRide:true, estimatedRepairCost:{min:150,max:600,currency:"SAR"} },
  "P0056": { code:"P0056", description:"O2 Sensor Heater Circuit Bank 2 Sensor 2", descriptionAr:"عطل في دائرة سخان حساس الأكسجين B2S2", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"low", causes:["Heater burned B2S2"], causesAr:["سخان محترق B2S2"], solution:"Replace O2 sensor B2S2 or check wiring", solutionAr:"استبدال حساس الأكسجين B2S2 أو فحص الأسلاك", relatedSensors:["O2 Sensor B2S2"], affectedComponents:["O2 Sensor B2S2"], affectedComponentsAr:["حساس الأكسجين الخلفي B2"], safeToRide:true, estimatedRepairCost:{min:150,max:600,currency:"SAR"} },

  // ══════════════════════════════════════════════
  // P0068–P0099 — حساس MAF / MAP / ضغط الهواء
  // ══════════════════════════════════════════════
  "P0068": { code:"P0068", description:"MAP/MAF Throttle Position Correlation", descriptionAr:"عدم تطابق بين حساسات MAP/MAF وموضع الخانق", system:"engine", subsystem:"Air Intake", subsystemAr:"نظام سحب الهواء", severity:"high", causes:["Air leak","MAF sensor fault","TPS fault","Vacuum leak"], causesAr:["تسريب هواء","عطل حساس MAF","عطل حساس TPS","تسريب فراغ"], solution:"Check for air leaks, test MAF and TPS sensors", solutionAr:"فحص تسريبات الهواء واختبار حساسات MAF وTPS", relatedSensors:["MAF Sensor","MAP Sensor","TPS"], affectedComponents:["Air Intake System"], affectedComponentsAr:["نظام سحب الهواء"], safeToRide:false, estimatedRepairCost:{min:200,max:1500,currency:"SAR"} },
  "P0069": { code:"P0069", description:"Manifold Absolute Pressure - Barometric Pressure Correlation", descriptionAr:"عدم تطابق بين ضغط المشعب وضغط الجو", system:"engine", subsystem:"Air Intake", subsystemAr:"نظام سحب الهواء", severity:"medium", causes:["MAP sensor fault","Vacuum leak","PCM fault"], causesAr:["عطل حساس MAP","تسريب فراغ","عطل PCM"], solution:"Test MAP sensor and check for vacuum leaks", solutionAr:"اختبار حساس MAP وفحص تسريبات الفراغ", relatedSensors:["MAP Sensor"], affectedComponents:["MAP Sensor"], affectedComponentsAr:["حساس ضغط المشعب"], safeToRide:true, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },

  // ══════════════════════════════════════════════
  // P0100–P0109 — حساس MAF
  // ══════════════════════════════════════════════
  "P0100": { code:"P0100", description:"Mass Air Flow Circuit Malfunction", descriptionAr:"عطل في دائرة حساس تدفق الهواء MAF", system:"engine", subsystem:"Air Intake", subsystemAr:"نظام سحب الهواء", severity:"high", causes:["MAF sensor dirty/faulty","Air leak after MAF","Wiring fault"], causesAr:["حساس MAF متسخ أو تالف","تسريب هواء بعد MAF","عطل أسلاك"], solution:"Clean MAF sensor with MAF cleaner, check for air leaks, replace if needed", solutionAr:"تنظيف حساس MAF بمنظف مخصص، فحص تسريبات الهواء، استبدال إذا لزم", relatedSensors:["MAF Sensor"], affectedComponents:["MAF Sensor"], affectedComponentsAr:["حساس تدفق الهواء"], safeToRide:false, estimatedRepairCost:{min:200,max:1200,currency:"SAR"} },
  "P0101": { code:"P0101", description:"Mass Air Flow Circuit Range/Performance", descriptionAr:"أداء حساس تدفق الهواء MAF خارج النطاق", system:"engine", subsystem:"Air Intake", subsystemAr:"نظام سحب الهواء", severity:"high", causes:["Dirty MAF sensor","Air filter clogged","Air leak","Vacuum leak"], causesAr:["حساس MAF متسخ","فلتر هواء مسدود","تسريب هواء","تسريب فراغ"], solution:"Clean or replace MAF sensor, replace air filter, check for leaks", solutionAr:"تنظيف أو استبدال حساس MAF، تغيير فلتر الهواء، فحص التسريبات", relatedSensors:["MAF Sensor"], affectedComponents:["MAF Sensor","Air Filter"], affectedComponentsAr:["حساس MAF","فلتر الهواء"], safeToRide:false, estimatedRepairCost:{min:200,max:1200,currency:"SAR"} },
  "P0102": { code:"P0102", description:"Mass Air Flow Circuit Low Input", descriptionAr:"إشارة منخفضة من حساس تدفق الهواء MAF", system:"engine", subsystem:"Air Intake", subsystemAr:"نظام سحب الهواء", severity:"high", causes:["MAF sensor faulty","Wiring short to ground","Air filter extremely clogged"], causesAr:["حساس MAF تالف","قصر أرضي في الأسلاك","فلتر هواء مسدود جداً"], solution:"Check MAF wiring for shorts, replace MAF sensor", solutionAr:"فحص أسلاك MAF للقصر، استبدال حساس MAF", relatedSensors:["MAF Sensor"], affectedComponents:["MAF Sensor"], affectedComponentsAr:["حساس تدفق الهواء"], safeToRide:false, estimatedRepairCost:{min:200,max:1200,currency:"SAR"} },
  "P0103": { code:"P0103", description:"Mass Air Flow Circuit High Input", descriptionAr:"إشارة مرتفعة من حساس تدفق الهواء MAF", system:"engine", subsystem:"Air Intake", subsystemAr:"نظام سحب الهواء", severity:"high", causes:["MAF sensor faulty","Wiring short to power","Air leak before MAF"], causesAr:["حساس MAF تالف","قصر للطاقة في الأسلاك","تسريب هواء قبل MAF"], solution:"Check MAF wiring, replace MAF sensor", solutionAr:"فحص أسلاك MAF، استبدال حساس MAF", relatedSensors:["MAF Sensor"], affectedComponents:["MAF Sensor"], affectedComponentsAr:["حساس تدفق الهواء"], safeToRide:false, estimatedRepairCost:{min:200,max:1200,currency:"SAR"} },
  "P0104": { code:"P0104", description:"Mass Air Flow Circuit Intermittent", descriptionAr:"إشارة متقطعة من حساس تدفق الهواء MAF", system:"engine", subsystem:"Air Intake", subsystemAr:"نظام سحب الهواء", severity:"medium", causes:["Loose MAF connector","Intermittent wiring fault","MAF sensor failing"], causesAr:["موصل MAF غير محكم","عطل أسلاك متقطع","حساس MAF يتعطل تدريجياً"], solution:"Check MAF connector and wiring, replace MAF sensor", solutionAr:"فحص موصل وأسلاك MAF، استبدال حساس MAF", relatedSensors:["MAF Sensor"], affectedComponents:["MAF Sensor"], affectedComponentsAr:["حساس تدفق الهواء"], safeToRide:true, estimatedRepairCost:{min:200,max:1200,currency:"SAR"} },

  // ══════════════════════════════════════════════
  // P0105–P0109 — حساس MAP
  // ══════════════════════════════════════════════
  "P0105": { code:"P0105", description:"Manifold Absolute Pressure Circuit Malfunction", descriptionAr:"عطل في دائرة حساس ضغط المشعب MAP", system:"engine", subsystem:"Air Intake", subsystemAr:"نظام سحب الهواء", severity:"high", causes:["MAP sensor faulty","Vacuum line cracked","Wiring fault"], causesAr:["حساس MAP تالف","خرطوم فراغ متشقق","عطل أسلاك"], solution:"Check vacuum line to MAP sensor, test sensor output", solutionAr:"فحص خرطوم الفراغ لحساس MAP واختبار إخراجه", relatedSensors:["MAP Sensor"], affectedComponents:["MAP Sensor"], affectedComponentsAr:["حساس ضغط المشعب"], safeToRide:false, estimatedRepairCost:{min:150,max:800,currency:"SAR"} },
  "P0106": { code:"P0106", description:"Manifold Absolute Pressure Range/Performance", descriptionAr:"أداء حساس ضغط المشعب MAP خارج النطاق", system:"engine", subsystem:"Air Intake", subsystemAr:"نظام سحب الهواء", severity:"high", causes:["Vacuum leak","MAP sensor dirty","Throttle body dirty"], causesAr:["تسريب فراغ","حساس MAP متسخ","جسم خانق متسخ"], solution:"Check vacuum system, clean throttle body, test MAP sensor", solutionAr:"فحص نظام الفراغ، تنظيف جسم الخانق، اختبار حساس MAP", relatedSensors:["MAP Sensor","TPS"], affectedComponents:["MAP Sensor","Throttle Body"], affectedComponentsAr:["حساس MAP","جسم الخانق"], safeToRide:false, estimatedRepairCost:{min:150,max:1000,currency:"SAR"} },
  "P0107": { code:"P0107", description:"Manifold Absolute Pressure Circuit Low Input", descriptionAr:"إشارة منخفضة من حساس ضغط المشعب MAP", system:"engine", subsystem:"Air Intake", subsystemAr:"نظام سحب الهواء", severity:"high", causes:["MAP sensor faulty","Vacuum line blocked","Short to ground"], causesAr:["حساس MAP تالف","خرطوم فراغ مسدود","قصر أرضي"], solution:"Check vacuum line and MAP sensor wiring", solutionAr:"فحص خرطوم الفراغ وأسلاك حساس MAP", relatedSensors:["MAP Sensor"], affectedComponents:["MAP Sensor"], affectedComponentsAr:["حساس ضغط المشعب"], safeToRide:false, estimatedRepairCost:{min:150,max:800,currency:"SAR"} },
  "P0108": { code:"P0108", description:"Manifold Absolute Pressure Circuit High Input", descriptionAr:"إشارة مرتفعة من حساس ضغط المشعب MAP", system:"engine", subsystem:"Air Intake", subsystemAr:"نظام سحب الهواء", severity:"high", causes:["MAP sensor faulty","Vacuum line disconnected","Short to power"], causesAr:["حساس MAP تالف","خرطوم فراغ منفصل","قصر للطاقة"], solution:"Check vacuum line connection and MAP sensor", solutionAr:"فحص توصيل خرطوم الفراغ وحساس MAP", relatedSensors:["MAP Sensor"], affectedComponents:["MAP Sensor"], affectedComponentsAr:["حساس ضغط المشعب"], safeToRide:false, estimatedRepairCost:{min:150,max:800,currency:"SAR"} },
  "P0109": { code:"P0109", description:"Manifold Absolute Pressure Circuit Intermittent", descriptionAr:"إشارة متقطعة من حساس ضغط المشعب MAP", system:"engine", subsystem:"Air Intake", subsystemAr:"نظام سحب الهواء", severity:"medium", causes:["Loose MAP connector","Intermittent vacuum leak"], causesAr:["موصل MAP غير محكم","تسريب فراغ متقطع"], solution:"Check MAP connector and vacuum line", solutionAr:"فحص موصل MAP وخرطوم الفراغ", relatedSensors:["MAP Sensor"], affectedComponents:["MAP Sensor"], affectedComponentsAr:["حساس ضغط المشعب"], safeToRide:true, estimatedRepairCost:{min:150,max:800,currency:"SAR"} },

  // ══════════════════════════════════════════════
  // P0110–P0119 — حساس درجة حرارة الهواء IAT
  // ══════════════════════════════════════════════
  "P0110": { code:"P0110", description:"Intake Air Temperature Circuit Malfunction", descriptionAr:"عطل في دائرة حساس درجة حرارة الهواء IAT", system:"engine", subsystem:"Air Intake", subsystemAr:"نظام سحب الهواء", severity:"medium", causes:["IAT sensor faulty","Wiring fault","PCM fault"], causesAr:["حساس IAT تالف","عطل أسلاك","عطل PCM"], solution:"Test IAT sensor resistance, check wiring", solutionAr:"قياس مقاومة حساس IAT وفحص الأسلاك", relatedSensors:["IAT Sensor"], affectedComponents:["IAT Sensor"], affectedComponentsAr:["حساس درجة حرارة الهواء"], safeToRide:true, estimatedRepairCost:{min:100,max:500,currency:"SAR"} },
  "P0111": { code:"P0111", description:"Intake Air Temperature Circuit Range/Performance", descriptionAr:"أداء حساس درجة حرارة الهواء IAT خارج النطاق", system:"engine", subsystem:"Air Intake", subsystemAr:"نظام سحب الهواء", severity:"medium", causes:["IAT sensor slow response","Contaminated sensor"], causesAr:["استجابة بطيئة لحساس IAT","حساس ملوث"], solution:"Clean or replace IAT sensor", solutionAr:"تنظيف أو استبدال حساس IAT", relatedSensors:["IAT Sensor"], affectedComponents:["IAT Sensor"], affectedComponentsAr:["حساس درجة حرارة الهواء"], safeToRide:true, estimatedRepairCost:{min:100,max:500,currency:"SAR"} },
  "P0112": { code:"P0112", description:"Intake Air Temperature Circuit Low Input", descriptionAr:"إشارة منخفضة من حساس درجة حرارة الهواء IAT", system:"engine", subsystem:"Air Intake", subsystemAr:"نظام سحب الهواء", severity:"medium", causes:["IAT sensor short to ground","Sensor faulty"], causesAr:["قصر أرضي في حساس IAT","حساس تالف"], solution:"Check IAT sensor wiring for short to ground", solutionAr:"فحص أسلاك حساس IAT للقصر الأرضي", relatedSensors:["IAT Sensor"], affectedComponents:["IAT Sensor"], affectedComponentsAr:["حساس درجة حرارة الهواء"], safeToRide:true, estimatedRepairCost:{min:100,max:500,currency:"SAR"} },
  "P0113": { code:"P0113", description:"Intake Air Temperature Circuit High Input", descriptionAr:"إشارة مرتفعة من حساس درجة حرارة الهواء IAT", system:"engine", subsystem:"Air Intake", subsystemAr:"نظام سحب الهواء", severity:"medium", causes:["IAT sensor open circuit","Connector loose","Sensor faulty"], causesAr:["دائرة مفتوحة في حساس IAT","موصل غير محكم","حساس تالف"], solution:"Check IAT connector and replace sensor if needed", solutionAr:"فحص موصل IAT واستبدال الحساس إذا لزم", relatedSensors:["IAT Sensor"], affectedComponents:["IAT Sensor"], affectedComponentsAr:["حساس درجة حرارة الهواء"], safeToRide:true, estimatedRepairCost:{min:100,max:500,currency:"SAR"} },
  "P0114": { code:"P0114", description:"Intake Air Temperature Circuit Intermittent", descriptionAr:"إشارة متقطعة من حساس درجة حرارة الهواء IAT", system:"engine", subsystem:"Air Intake", subsystemAr:"نظام سحب الهواء", severity:"low", causes:["Loose IAT connector","Intermittent wiring fault"], causesAr:["موصل IAT غير محكم","عطل أسلاك متقطع"], solution:"Check IAT connector and wiring", solutionAr:"فحص موصل وأسلاك IAT", relatedSensors:["IAT Sensor"], affectedComponents:["IAT Sensor"], affectedComponentsAr:["حساس درجة حرارة الهواء"], safeToRide:true, estimatedRepairCost:{min:100,max:500,currency:"SAR"} },

  // ══════════════════════════════════════════════
  // P0115–P0129 — حساس درجة حرارة سائل التبريد ECT
  // ══════════════════════════════════════════════
  "P0115": { code:"P0115", description:"Engine Coolant Temperature Circuit Malfunction", descriptionAr:"عطل في دائرة حساس درجة حرارة سائل التبريد ECT", system:"engine", subsystem:"Cooling System", subsystemAr:"نظام التبريد", severity:"high", causes:["ECT sensor faulty","Wiring fault","Low coolant level"], causesAr:["حساس ECT تالف","عطل أسلاك","مستوى سائل تبريد منخفض"], solution:"Test ECT sensor resistance, check coolant level", solutionAr:"قياس مقاومة حساس ECT وفحص مستوى سائل التبريد", relatedSensors:["ECT Sensor"], affectedComponents:["ECT Sensor"], affectedComponentsAr:["حساس درجة حرارة سائل التبريد"], safeToRide:false, estimatedRepairCost:{min:100,max:600,currency:"SAR"} },
  "P0116": { code:"P0116", description:"Engine Coolant Temperature Circuit Range/Performance", descriptionAr:"أداء حساس درجة حرارة سائل التبريد ECT خارج النطاق", system:"engine", subsystem:"Cooling System", subsystemAr:"نظام التبريد", severity:"high", causes:["Thermostat stuck open","ECT sensor faulty","Low coolant"], causesAr:["ترموستات عالق مفتوح","حساس ECT تالف","سائل تبريد منخفض"], solution:"Check thermostat operation, test ECT sensor", solutionAr:"فحص عمل الترموستات واختبار حساس ECT", relatedSensors:["ECT Sensor"], affectedComponents:["Thermostat","ECT Sensor"], affectedComponentsAr:["الترموستات","حساس ECT"], safeToRide:false, estimatedRepairCost:{min:200,max:1000,currency:"SAR"} },
  "P0117": { code:"P0117", description:"Engine Coolant Temperature Circuit Low Input", descriptionAr:"إشارة منخفضة من حساس درجة حرارة سائل التبريد", system:"engine", subsystem:"Cooling System", subsystemAr:"نظام التبريد", severity:"high", causes:["ECT sensor short to ground","Sensor faulty"], causesAr:["قصر أرضي في حساس ECT","حساس تالف"], solution:"Check ECT wiring for short to ground, replace sensor", solutionAr:"فحص أسلاك ECT للقصر الأرضي، استبدال الحساس", relatedSensors:["ECT Sensor"], affectedComponents:["ECT Sensor"], affectedComponentsAr:["حساس درجة حرارة سائل التبريد"], safeToRide:false, estimatedRepairCost:{min:100,max:600,currency:"SAR"} },
  "P0118": { code:"P0118", description:"Engine Coolant Temperature Circuit High Input", descriptionAr:"إشارة مرتفعة من حساس درجة حرارة سائل التبريد", system:"engine", subsystem:"Cooling System", subsystemAr:"نظام التبريد", severity:"high", causes:["ECT sensor open circuit","Connector loose","Sensor faulty"], causesAr:["دائرة مفتوحة في حساس ECT","موصل غير محكم","حساس تالف"], solution:"Check ECT connector and replace sensor", solutionAr:"فحص موصل ECT واستبدال الحساس", relatedSensors:["ECT Sensor"], affectedComponents:["ECT Sensor"], affectedComponentsAr:["حساس درجة حرارة سائل التبريد"], safeToRide:false, estimatedRepairCost:{min:100,max:600,currency:"SAR"} },
  "P0119": { code:"P0119", description:"Engine Coolant Temperature Circuit Intermittent", descriptionAr:"إشارة متقطعة من حساس درجة حرارة سائل التبريد", system:"engine", subsystem:"Cooling System", subsystemAr:"نظام التبريد", severity:"medium", causes:["Loose ECT connector","Intermittent wiring"], causesAr:["موصل ECT غير محكم","أسلاك متقطعة"], solution:"Check ECT connector and wiring", solutionAr:"فحص موصل وأسلاك ECT", relatedSensors:["ECT Sensor"], affectedComponents:["ECT Sensor"], affectedComponentsAr:["حساس درجة حرارة سائل التبريد"], safeToRide:false, estimatedRepairCost:{min:100,max:600,currency:"SAR"} },
  "P0125": { code:"P0125", description:"Insufficient Coolant Temperature for Closed Loop Fuel Control", descriptionAr:"درجة حرارة سائل التبريد غير كافية للتحكم المغلق بالوقود", system:"engine", subsystem:"Cooling System", subsystemAr:"نظام التبريد", severity:"medium", causes:["Thermostat stuck open","ECT sensor faulty","Low coolant level"], causesAr:["ترموستات عالق مفتوح","حساس ECT تالف","سائل تبريد منخفض"], solution:"Replace thermostat, test ECT sensor", solutionAr:"استبدال الترموستات واختبار حساس ECT", relatedSensors:["ECT Sensor"], affectedComponents:["Thermostat"], affectedComponentsAr:["الترموستات"], safeToRide:true, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },
  "P0128": { code:"P0128", description:"Coolant Temperature Below Thermostat Regulating Temperature", descriptionAr:"درجة حرارة سائل التبريد أقل من درجة حرارة الترموستات", system:"engine", subsystem:"Cooling System", subsystemAr:"نظام التبريد", severity:"medium", causes:["Thermostat stuck open","ECT sensor inaccurate"], causesAr:["ترموستات عالق مفتوح","حساس ECT غير دقيق"], solution:"Replace thermostat", solutionAr:"استبدال الترموستات", relatedSensors:["ECT Sensor"], affectedComponents:["Thermostat"], affectedComponentsAr:["الترموستات"], safeToRide:true, estimatedRepairCost:{min:150,max:600,currency:"SAR"} },
  "P0129": { code:"P0129", description:"Barometric Pressure Too Low", descriptionAr:"ضغط الجو منخفض جداً", system:"engine", subsystem:"Air Intake", subsystemAr:"نظام سحب الهواء", severity:"low", causes:["MAP/BARO sensor fault","High altitude driving"], causesAr:["عطل حساس MAP/BARO","القيادة على ارتفاع عالٍ"], solution:"Test MAP/BARO sensor", solutionAr:"اختبار حساس MAP/BARO", relatedSensors:["MAP Sensor","BARO Sensor"], affectedComponents:["MAP Sensor"], affectedComponentsAr:["حساس ضغط الجو"], safeToRide:true, estimatedRepairCost:{min:150,max:800,currency:"SAR"} },

  // ══════════════════════════════════════════════
  // P0130–P0167 — حساسات الأكسجين O2
  // ══════════════════════════════════════════════
  "P0130": { code:"P0130", description:"O2 Sensor Circuit Malfunction Bank 1 Sensor 1", descriptionAr:"عطل في دائرة حساس الأكسجين B1S1", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"high", causes:["O2 sensor faulty","Exhaust leak near sensor","Wiring fault"], causesAr:["حساس O2 تالف","تسريب عادم قرب الحساس","عطل أسلاك"], solution:"Check for exhaust leaks, test O2 sensor output, replace if needed", solutionAr:"فحص تسريبات العادم، اختبار إخراج حساس O2، استبدال إذا لزم", relatedSensors:["O2 Sensor B1S1"], affectedComponents:["O2 Sensor B1S1"], affectedComponentsAr:["حساس الأكسجين الأمامي B1"], safeToRide:false, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },
  "P0131": { code:"P0131", description:"O2 Sensor Circuit Low Voltage Bank 1 Sensor 1", descriptionAr:"جهد منخفض في حساس الأكسجين B1S1", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"high", causes:["Lean fuel mixture","O2 sensor faulty","Exhaust leak","Vacuum leak"], causesAr:["خليط وقود فقير","حساس O2 تالف","تسريب عادم","تسريب فراغ"], solution:"Check fuel system for lean condition, inspect exhaust for leaks", solutionAr:"فحص نظام الوقود للخليط الفقير، فحص العادم للتسريبات", relatedSensors:["O2 Sensor B1S1"], affectedComponents:["O2 Sensor B1S1"], affectedComponentsAr:["حساس الأكسجين الأمامي B1"], safeToRide:false, estimatedRepairCost:{min:200,max:1000,currency:"SAR"} },
  "P0132": { code:"P0132", description:"O2 Sensor Circuit High Voltage Bank 1 Sensor 1", descriptionAr:"جهد مرتفع في حساس الأكسجين B1S1", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"high", causes:["Rich fuel mixture","O2 sensor faulty","Fuel pressure too high"], causesAr:["خليط وقود غني","حساس O2 تالف","ضغط وقود مرتفع"], solution:"Check fuel system for rich condition, test O2 sensor", solutionAr:"فحص نظام الوقود للخليط الغني، اختبار حساس O2", relatedSensors:["O2 Sensor B1S1"], affectedComponents:["O2 Sensor B1S1"], affectedComponentsAr:["حساس الأكسجين الأمامي B1"], safeToRide:false, estimatedRepairCost:{min:200,max:1000,currency:"SAR"} },
  "P0133": { code:"P0133", description:"O2 Sensor Circuit Slow Response Bank 1 Sensor 1", descriptionAr:"استجابة بطيئة لحساس الأكسجين B1S1", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"medium", causes:["O2 sensor aging","Contaminated sensor","Exhaust leak"], causesAr:["حساس O2 متقادم","حساس ملوث","تسريب عادم"], solution:"Replace O2 sensor B1S1", solutionAr:"استبدال حساس الأكسجين B1S1", relatedSensors:["O2 Sensor B1S1"], affectedComponents:["O2 Sensor B1S1"], affectedComponentsAr:["حساس الأكسجين الأمامي B1"], safeToRide:true, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },
  "P0134": { code:"P0134", description:"O2 Sensor Circuit No Activity Bank 1 Sensor 1", descriptionAr:"لا نشاط في حساس الأكسجين B1S1", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"high", causes:["O2 sensor dead","Heater not working","Wiring fault"], causesAr:["حساس O2 ميت","سخان لا يعمل","عطل أسلاك"], solution:"Check heater circuit, replace O2 sensor", solutionAr:"فحص دائرة السخان، استبدال حساس O2", relatedSensors:["O2 Sensor B1S1"], affectedComponents:["O2 Sensor B1S1"], affectedComponentsAr:["حساس الأكسجين الأمامي B1"], safeToRide:false, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },
  "P0135": { code:"P0135", description:"O2 Sensor Heater Circuit Malfunction Bank 1 Sensor 1", descriptionAr:"عطل في سخان حساس الأكسجين B1S1", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"medium", causes:["Heater element burned","Blown fuse","Wiring fault"], causesAr:["عنصر السخان محترق","فيوز محترق","عطل أسلاك"], solution:"Check heater fuse and circuit, replace O2 sensor", solutionAr:"فحص فيوز وداءرة السخان، استبدال حساس O2", relatedSensors:["O2 Sensor B1S1"], affectedComponents:["O2 Sensor Heater"], affectedComponentsAr:["سخان حساس O2"], safeToRide:true, estimatedRepairCost:{min:150,max:600,currency:"SAR"} },
  "P0136": { code:"P0136", description:"O2 Sensor Circuit Malfunction Bank 1 Sensor 2", descriptionAr:"عطل في دائرة حساس الأكسجين الخلفي B1S2", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"medium", causes:["Rear O2 sensor faulty","Wiring fault","Catalytic converter issue"], causesAr:["حساس O2 الخلفي تالف","عطل أسلاك","مشكلة في المحول الحفاز"], solution:"Test rear O2 sensor, check catalytic converter", solutionAr:"اختبار حساس O2 الخلفي وفحص المحول الحفاز", relatedSensors:["O2 Sensor B1S2"], affectedComponents:["O2 Sensor B1S2","Catalytic Converter"], affectedComponentsAr:["حساس O2 الخلفي","المحول الحفاز"], safeToRide:true, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },
  "P0137": { code:"P0137", description:"O2 Sensor Circuit Low Voltage Bank 1 Sensor 2", descriptionAr:"جهد منخفض في حساس الأكسجين الخلفي B1S2", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"medium", causes:["Rear O2 sensor faulty","Lean exhaust after catalyst"], causesAr:["حساس O2 الخلفي تالف","عادم فقير بعد المحول"], solution:"Replace rear O2 sensor", solutionAr:"استبدال حساس O2 الخلفي", relatedSensors:["O2 Sensor B1S2"], affectedComponents:["O2 Sensor B1S2"], affectedComponentsAr:["حساس O2 الخلفي B1"], safeToRide:true, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },
  "P0138": { code:"P0138", description:"O2 Sensor Circuit High Voltage Bank 1 Sensor 2", descriptionAr:"جهد مرتفع في حساس الأكسجين الخلفي B1S2", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"medium", causes:["Rear O2 sensor faulty","Rich exhaust after catalyst","Leaking injector"], causesAr:["حساس O2 الخلفي تالف","عادم غني بعد المحول","حاقن يسرب"], solution:"Check for rich condition, replace rear O2 sensor", solutionAr:"فحص الخليط الغني، استبدال حساس O2 الخلفي", relatedSensors:["O2 Sensor B1S2"], affectedComponents:["O2 Sensor B1S2"], affectedComponentsAr:["حساس O2 الخلفي B1"], safeToRide:true, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },
  "P0139": { code:"P0139", description:"O2 Sensor Circuit Slow Response Bank 1 Sensor 2", descriptionAr:"استجابة بطيئة لحساس الأكسجين الخلفي B1S2", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"low", causes:["Rear O2 sensor aging","Catalytic converter degraded"], causesAr:["حساس O2 الخلفي متقادم","تدهور المحول الحفاز"], solution:"Replace rear O2 sensor, check catalytic converter", solutionAr:"استبدال حساس O2 الخلفي وفحص المحول الحفاز", relatedSensors:["O2 Sensor B1S2"], affectedComponents:["O2 Sensor B1S2"], affectedComponentsAr:["حساس O2 الخلفي B1"], safeToRide:true, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },
  "P0140": { code:"P0140", description:"O2 Sensor Circuit No Activity Bank 1 Sensor 2", descriptionAr:"لا نشاط في حساس الأكسجين الخلفي B1S2", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"medium", causes:["Rear O2 sensor dead","Heater not working"], causesAr:["حساس O2 الخلفي ميت","سخان لا يعمل"], solution:"Check heater circuit, replace rear O2 sensor", solutionAr:"فحص دائرة السخان، استبدال حساس O2 الخلفي", relatedSensors:["O2 Sensor B1S2"], affectedComponents:["O2 Sensor B1S2"], affectedComponentsAr:["حساس O2 الخلفي B1"], safeToRide:true, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },
  "P0141": { code:"P0141", description:"O2 Sensor Heater Circuit Malfunction Bank 1 Sensor 2", descriptionAr:"عطل في سخان حساس الأكسجين الخلفي B1S2", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"low", causes:["Heater element burned","Blown fuse"], causesAr:["عنصر السخان محترق","فيوز محترق"], solution:"Check heater fuse and circuit, replace rear O2 sensor", solutionAr:"فحص فيوز وداءرة السخان، استبدال حساس O2 الخلفي", relatedSensors:["O2 Sensor B1S2"], affectedComponents:["O2 Sensor B1S2"], affectedComponentsAr:["حساس O2 الخلفي B1"], safeToRide:true, estimatedRepairCost:{min:150,max:600,currency:"SAR"} },
  "P0150": { code:"P0150", description:"O2 Sensor Circuit Malfunction Bank 2 Sensor 1", descriptionAr:"عطل في دائرة حساس الأكسجين B2S1", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"high", causes:["O2 sensor B2S1 faulty","Exhaust leak","Wiring fault"], causesAr:["حساس O2 B2S1 تالف","تسريب عادم","عطل أسلاك"], solution:"Check exhaust leaks, replace O2 sensor B2S1", solutionAr:"فحص تسريبات العادم، استبدال حساس O2 B2S1", relatedSensors:["O2 Sensor B2S1"], affectedComponents:["O2 Sensor B2S1"], affectedComponentsAr:["حساس O2 الأمامي B2"], safeToRide:false, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },
  "P0151": { code:"P0151", description:"O2 Sensor Circuit Low Voltage Bank 2 Sensor 1", descriptionAr:"جهد منخفض في حساس الأكسجين B2S1", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"high", causes:["Lean mixture B2","O2 sensor faulty","Exhaust leak B2"], causesAr:["خليط فقير البنك 2","حساس O2 تالف","تسريب عادم البنك 2"], solution:"Check fuel system B2, replace O2 sensor B2S1", solutionAr:"فحص نظام الوقود البنك 2، استبدال حساس O2 B2S1", relatedSensors:["O2 Sensor B2S1"], affectedComponents:["O2 Sensor B2S1"], affectedComponentsAr:["حساس O2 الأمامي B2"], safeToRide:false, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },
  "P0152": { code:"P0152", description:"O2 Sensor Circuit High Voltage Bank 2 Sensor 1", descriptionAr:"جهد مرتفع في حساس الأكسجين B2S1", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"high", causes:["Rich mixture B2","O2 sensor faulty"], causesAr:["خليط غني البنك 2","حساس O2 تالف"], solution:"Check fuel system B2, replace O2 sensor B2S1", solutionAr:"فحص نظام الوقود البنك 2، استبدال حساس O2 B2S1", relatedSensors:["O2 Sensor B2S1"], affectedComponents:["O2 Sensor B2S1"], affectedComponentsAr:["حساس O2 الأمامي B2"], safeToRide:false, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },
  "P0153": { code:"P0153", description:"O2 Sensor Circuit Slow Response Bank 2 Sensor 1", descriptionAr:"استجابة بطيئة لحساس الأكسجين B2S1", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"medium", causes:["O2 sensor B2S1 aging"], causesAr:["حساس O2 B2S1 متقادم"], solution:"Replace O2 sensor B2S1", solutionAr:"استبدال حساس O2 B2S1", relatedSensors:["O2 Sensor B2S1"], affectedComponents:["O2 Sensor B2S1"], affectedComponentsAr:["حساس O2 الأمامي B2"], safeToRide:true, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },
  "P0154": { code:"P0154", description:"O2 Sensor Circuit No Activity Bank 2 Sensor 1", descriptionAr:"لا نشاط في حساس الأكسجين B2S1", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"high", causes:["O2 sensor B2S1 dead","Heater not working"], causesAr:["حساس O2 B2S1 ميت","سخان لا يعمل"], solution:"Check heater, replace O2 sensor B2S1", solutionAr:"فحص السخان، استبدال حساس O2 B2S1", relatedSensors:["O2 Sensor B2S1"], affectedComponents:["O2 Sensor B2S1"], affectedComponentsAr:["حساس O2 الأمامي B2"], safeToRide:false, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },
  "P0155": { code:"P0155", description:"O2 Sensor Heater Circuit Malfunction Bank 2 Sensor 1", descriptionAr:"عطل في سخان حساس الأكسجين B2S1", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"medium", causes:["Heater burned B2S1","Fuse blown"], causesAr:["سخان محترق B2S1","فيوز محترق"], solution:"Check heater fuse, replace O2 sensor B2S1", solutionAr:"فحص فيوز السخان، استبدال حساس O2 B2S1", relatedSensors:["O2 Sensor B2S1"], affectedComponents:["O2 Sensor B2S1"], affectedComponentsAr:["حساس O2 الأمامي B2"], safeToRide:true, estimatedRepairCost:{min:150,max:600,currency:"SAR"} },
  "P0156": { code:"P0156", description:"O2 Sensor Circuit Malfunction Bank 2 Sensor 2", descriptionAr:"عطل في دائرة حساس الأكسجين الخلفي B2S2", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"medium", causes:["Rear O2 sensor B2S2 faulty","Wiring fault"], causesAr:["حساس O2 الخلفي B2S2 تالف","عطل أسلاك"], solution:"Test and replace rear O2 sensor B2S2", solutionAr:"اختبار واستبدال حساس O2 الخلفي B2S2", relatedSensors:["O2 Sensor B2S2"], affectedComponents:["O2 Sensor B2S2"], affectedComponentsAr:["حساس O2 الخلفي B2"], safeToRide:true, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },
  "P0157": { code:"P0157", description:"O2 Sensor Circuit Low Voltage Bank 2 Sensor 2", descriptionAr:"جهد منخفض في حساس الأكسجين الخلفي B2S2", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"medium", causes:["Rear O2 sensor B2S2 faulty"], causesAr:["حساس O2 الخلفي B2S2 تالف"], solution:"Replace rear O2 sensor B2S2", solutionAr:"استبدال حساس O2 الخلفي B2S2", relatedSensors:["O2 Sensor B2S2"], affectedComponents:["O2 Sensor B2S2"], affectedComponentsAr:["حساس O2 الخلفي B2"], safeToRide:true, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },
  "P0158": { code:"P0158", description:"O2 Sensor Circuit High Voltage Bank 2 Sensor 2", descriptionAr:"جهد مرتفع في حساس الأكسجين الخلفي B2S2", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"medium", causes:["Rear O2 sensor B2S2 faulty","Rich exhaust B2"], causesAr:["حساس O2 الخلفي B2S2 تالف","عادم غني البنك 2"], solution:"Replace rear O2 sensor B2S2", solutionAr:"استبدال حساس O2 الخلفي B2S2", relatedSensors:["O2 Sensor B2S2"], affectedComponents:["O2 Sensor B2S2"], affectedComponentsAr:["حساس O2 الخلفي B2"], safeToRide:true, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },
  "P0159": { code:"P0159", description:"O2 Sensor Circuit Slow Response Bank 2 Sensor 2", descriptionAr:"استجابة بطيئة لحساس الأكسجين الخلفي B2S2", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"low", causes:["Rear O2 sensor B2S2 aging"], causesAr:["حساس O2 الخلفي B2S2 متقادم"], solution:"Replace rear O2 sensor B2S2", solutionAr:"استبدال حساس O2 الخلفي B2S2", relatedSensors:["O2 Sensor B2S2"], affectedComponents:["O2 Sensor B2S2"], affectedComponentsAr:["حساس O2 الخلفي B2"], safeToRide:true, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },
  "P0160": { code:"P0160", description:"O2 Sensor Circuit No Activity Bank 2 Sensor 2", descriptionAr:"لا نشاط في حساس الأكسجين الخلفي B2S2", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"medium", causes:["Rear O2 sensor B2S2 dead"], causesAr:["حساس O2 الخلفي B2S2 ميت"], solution:"Replace rear O2 sensor B2S2", solutionAr:"استبدال حساس O2 الخلفي B2S2", relatedSensors:["O2 Sensor B2S2"], affectedComponents:["O2 Sensor B2S2"], affectedComponentsAr:["حساس O2 الخلفي B2"], safeToRide:true, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },
  "P0161": { code:"P0161", description:"O2 Sensor Heater Circuit Malfunction Bank 2 Sensor 2", descriptionAr:"عطل في سخان حساس الأكسجين الخلفي B2S2", system:"engine", subsystem:"O2 Sensors", subsystemAr:"حساسات الأكسجين", severity:"low", causes:["Heater burned B2S2"], causesAr:["سخان محترق B2S2"], solution:"Check heater fuse, replace O2 sensor B2S2", solutionAr:"فحص فيوز السخان، استبدال حساس O2 B2S2", relatedSensors:["O2 Sensor B2S2"], affectedComponents:["O2 Sensor B2S2"], affectedComponentsAr:["حساس O2 الخلفي B2"], safeToRide:true, estimatedRepairCost:{min:150,max:600,currency:"SAR"} },

  // ══════════════════════════════════════════════
  // P0170–P0179 — نظام الوقود (خليط غني/فقير)
  // ══════════════════════════════════════════════
  "P0170": { code:"P0170", description:"Fuel Trim Malfunction Bank 1", descriptionAr:"عطل في ضبط الوقود - البنك 1", system:"engine", subsystem:"Fuel System", subsystemAr:"نظام الوقود", severity:"high", causes:["MAF sensor faulty","Vacuum leak","Injector fault","O2 sensor fault"], causesAr:["حساس MAF تالف","تسريب فراغ","عطل حاقن","عطل حساس O2"], solution:"Check fuel trim values, inspect MAF and O2 sensors, check for vacuum leaks", solutionAr:"فحص قيم ضبط الوقود، فحص حساسات MAF وO2، فحص تسريبات الفراغ", relatedSensors:["MAF Sensor","O2 Sensor B1S1"], affectedComponents:["Fuel Injectors","MAF Sensor"], affectedComponentsAr:["حاقنات الوقود","حساس MAF"], safeToRide:false, estimatedRepairCost:{min:200,max:2000,currency:"SAR"} },
  "P0171": { code:"P0171", description:"System Too Lean Bank 1", descriptionAr:"خليط الوقود فقير جداً - البنك 1", system:"engine", subsystem:"Fuel System", subsystemAr:"نظام الوقود", severity:"high", causes:["Vacuum leak","MAF sensor dirty","Low fuel pressure","Clogged injector","PCV valve fault"], causesAr:["تسريب فراغ","حساس MAF متسخ","ضغط وقود منخفض","حاقن مسدود","عطل صمام PCV"], solution:"Check for vacuum leaks, clean MAF sensor, test fuel pressure and injectors", solutionAr:"فحص تسريبات الفراغ، تنظيف حساس MAF، اختبار ضغط الوقود والحاقنات", relatedSensors:["MAF Sensor","O2 Sensor B1S1"], affectedComponents:["MAF Sensor","Fuel Injectors","PCV Valve"], affectedComponentsAr:["حساس MAF","حاقنات الوقود","صمام PCV"], safeToRide:false, estimatedRepairCost:{min:200,max:2000,currency:"SAR"} },
  "P0172": { code:"P0172", description:"System Too Rich Bank 1", descriptionAr:"خليط الوقود غني جداً - البنك 1", system:"engine", subsystem:"Fuel System", subsystemAr:"نظام الوقود", severity:"high", causes:["Leaking injector","High fuel pressure","O2 sensor faulty","EVAP purge valve stuck open","Coolant temp sensor faulty"], causesAr:["حاقن يسرب","ضغط وقود مرتفع","حساس O2 تالف","صمام EVAP عالق مفتوح","حساس درجة حرارة سائل التبريد تالف"], solution:"Check fuel pressure, test injectors for leaks, inspect EVAP system", solutionAr:"فحص ضغط الوقود، اختبار الحاقنات للتسريب، فحص نظام EVAP", relatedSensors:["O2 Sensor B1S1","ECT Sensor"], affectedComponents:["Fuel Injectors","Fuel Pressure Regulator","EVAP Purge Valve"], affectedComponentsAr:["حاقنات الوقود","منظم ضغط الوقود","صمام EVAP"], safeToRide:false, estimatedRepairCost:{min:300,max:2500,currency:"SAR"} },
  "P0173": { code:"P0173", description:"Fuel Trim Malfunction Bank 2", descriptionAr:"عطل في ضبط الوقود - البنك 2", system:"engine", subsystem:"Fuel System", subsystemAr:"نظام الوقود", severity:"high", causes:["MAF sensor faulty B2","Vacuum leak B2","Injector fault B2"], causesAr:["حساس MAF تالف البنك 2","تسريب فراغ البنك 2","عطل حاقن البنك 2"], solution:"Check fuel trim B2, inspect MAF and O2 sensors B2", solutionAr:"فحص ضبط الوقود البنك 2، فحص حساسات MAF وO2 البنك 2", relatedSensors:["MAF Sensor","O2 Sensor B2S1"], affectedComponents:["Fuel Injectors B2"], affectedComponentsAr:["حاقنات الوقود البنك 2"], safeToRide:false, estimatedRepairCost:{min:200,max:2000,currency:"SAR"} },
  "P0174": { code:"P0174", description:"System Too Lean Bank 2", descriptionAr:"خليط الوقود فقير جداً - البنك 2", system:"engine", subsystem:"Fuel System", subsystemAr:"نظام الوقود", severity:"high", causes:["Vacuum leak B2","MAF sensor dirty","Low fuel pressure B2","Clogged injector B2"], causesAr:["تسريب فراغ البنك 2","حساس MAF متسخ","ضغط وقود منخفض البنك 2","حاقن مسدود البنك 2"], solution:"Check for vacuum leaks B2, clean MAF sensor, test fuel pressure", solutionAr:"فحص تسريبات الفراغ البنك 2، تنظيف حساس MAF، اختبار ضغط الوقود", relatedSensors:["MAF Sensor","O2 Sensor B2S1"], affectedComponents:["MAF Sensor","Fuel Injectors B2"], affectedComponentsAr:["حساس MAF","حاقنات الوقود البنك 2"], safeToRide:false, estimatedRepairCost:{min:200,max:2000,currency:"SAR"} },
  "P0175": { code:"P0175", description:"System Too Rich Bank 2", descriptionAr:"خليط الوقود غني جداً - البنك 2", system:"engine", subsystem:"Fuel System", subsystemAr:"نظام الوقود", severity:"high", causes:["Leaking injector B2","High fuel pressure","O2 sensor B2 faulty"], causesAr:["حاقن يسرب البنك 2","ضغط وقود مرتفع","حساس O2 البنك 2 تالف"], solution:"Check fuel pressure, test injectors B2 for leaks", solutionAr:"فحص ضغط الوقود، اختبار حاقنات البنك 2 للتسريب", relatedSensors:["O2 Sensor B2S1"], affectedComponents:["Fuel Injectors B2","Fuel Pressure Regulator"], affectedComponentsAr:["حاقنات الوقود البنك 2","منظم ضغط الوقود"], safeToRide:false, estimatedRepairCost:{min:300,max:2500,currency:"SAR"} },
  "P0176": { code:"P0176", description:"Fuel Composition Sensor Circuit Malfunction", descriptionAr:"عطل في دائرة حساس تركيبة الوقود (Flex Fuel)", system:"engine", subsystem:"Fuel System", subsystemAr:"نظام الوقود", severity:"medium", causes:["Flex fuel sensor faulty","Wiring fault"], causesAr:["حساس الوقود المرن تالف","عطل أسلاك"], solution:"Test flex fuel sensor and wiring", solutionAr:"اختبار حساس الوقود المرن والأسلاك", relatedSensors:["Flex Fuel Sensor"], affectedComponents:["Flex Fuel Sensor"], affectedComponentsAr:["حساس الوقود المرن"], safeToRide:true, estimatedRepairCost:{min:200,max:800,currency:"SAR"} },

  // ══════════════════════════════════════════════
  // P0180–P0199 — حساس درجة حرارة الوقود
  // ══════════════════════════════════════════════
  "P0180": { code:"P0180", description:"Fuel Temperature Sensor Circuit Malfunction", descriptionAr:"عطل في دائرة حساس درجة حرارة الوقود", system:"engine", subsystem:"Fuel System", subsystemAr:"نظام الوقود", severity:"medium", causes:["Fuel temp sensor faulty","Wiring fault"], causesAr:["حساس درجة حرارة الوقود تالف","عطل أسلاك"], solution:"Test fuel temperature sensor and wiring", solutionAr:"اختبار حساس درجة حرارة الوقود والأسلاك", relatedSensors:["Fuel Temp Sensor"], affectedComponents:["Fuel Temp Sensor"], affectedComponentsAr:["حساس درجة حرارة الوقود"], safeToRide:true, estimatedRepairCost:{min:100,max:500,currency:"SAR"} },
  "P0181": { code:"P0181", description:"Fuel Temperature Sensor Range/Performance", descriptionAr:"أداء حساس درجة حرارة الوقود خارج النطاق", system:"engine", subsystem:"Fuel System", subsystemAr:"نظام الوقود", severity:"medium", causes:["Fuel temp sensor slow response","Contaminated sensor"], causesAr:["استجابة بطيئة لحساس درجة حرارة الوقود","حساس ملوث"], solution:"Replace fuel temperature sensor", solutionAr:"استبدال حساس درجة حرارة الوقود", relatedSensors:["Fuel Temp Sensor"], affectedComponents:["Fuel Temp Sensor"], affectedComponentsAr:["حساس درجة حرارة الوقود"], safeToRide:true, estimatedRepairCost:{min:100,max:500,currency:"SAR"} },
  "P0182": { code:"P0182", description:"Fuel Temperature Sensor Circuit Low Input", descriptionAr:"إشارة منخفضة من حساس درجة حرارة الوقود", system:"engine", subsystem:"Fuel System", subsystemAr:"نظام الوقود", severity:"medium", causes:["Short to ground","Sensor faulty"], causesAr:["قصر أرضي","حساس تالف"], solution:"Check for short to ground, replace sensor", solutionAr:"فحص القصر الأرضي، استبدال الحساس", relatedSensors:["Fuel Temp Sensor"], affectedComponents:["Fuel Temp Sensor"], affectedComponentsAr:["حساس درجة حرارة الوقود"], safeToRide:true, estimatedRepairCost:{min:100,max:500,currency:"SAR"} },
  "P0183": { code:"P0183", description:"Fuel Temperature Sensor Circuit High Input", descriptionAr:"إشارة مرتفعة من حساس درجة حرارة الوقود", system:"engine", subsystem:"Fuel System", subsystemAr:"نظام الوقود", severity:"medium", causes:["Open circuit","Sensor faulty"], causesAr:["دائرة مفتوحة","حساس تالف"], solution:"Check for open circuit, replace sensor", solutionAr:"فحص الدائرة المفتوحة، استبدال الحساس", relatedSensors:["Fuel Temp Sensor"], affectedComponents:["Fuel Temp Sensor"], affectedComponentsAr:["حساس درجة حرارة الوقود"], safeToRide:true, estimatedRepairCost:{min:100,max:500,currency:"SAR"} },

  // ══════════════════════════════════════════════
  // P0190–P0199 — حساس ضغط رامب الوقود
  // ══════════════════════════════════════════════
  "P0190": { code:"P0190", description:"Fuel Rail Pressure Sensor Circuit Malfunction", descriptionAr:"عطل في دائرة حساس ضغط رامب الوقود", system:"engine", subsystem:"Fuel System", subsystemAr:"نظام الوقود", severity:"high", causes:["FRP sensor faulty","Wiring fault","PCM fault"], causesAr:["حساس FRP تالف","عطل أسلاك","عطل PCM"], solution:"Test FRP sensor and wiring", solutionAr:"اختبار حساس FRP والأسلاك", relatedSensors:["FRP Sensor"], affectedComponents:["Fuel Rail Pressure Sensor"], affectedComponentsAr:["حساس ضغط رامب الوقود"], safeToRide:false, estimatedRepairCost:{min:200,max:1000,currency:"SAR"} },
  "P0191": { code:"P0191", description:"Fuel Rail Pressure Sensor Range/Performance", descriptionAr:"أداء حساس ضغط رامب الوقود خارج النطاق", system:"engine", subsystem:"Fuel System", subsystemAr:"نظام الوقود", severity:"high", causes:["Low fuel pressure","FRP sensor faulty","Fuel pump weak"], causesAr:["ضغط وقود منخفض","حساس FRP تالف","طرمبة وقود ضعيفة"], solution:"Test fuel pressure, check fuel pump", solutionAr:"اختبار ضغط الوقود وفحص طرمبة الوقود", relatedSensors:["FRP Sensor"], affectedComponents:["Fuel Rail Pressure Sensor","Fuel Pump"], affectedComponentsAr:["حساس ضغط رامب الوقود","طرمبة الوقود"], safeToRide:false, estimatedRepairCost:{min:300,max:2000,currency:"SAR"} },
  "P0192": { code:"P0192", description:"Fuel Rail Pressure Sensor Circuit Low Input", descriptionAr:"إشارة منخفضة من حساس ضغط رامب الوقود", system:"engine", subsystem:"Fuel System", subsystemAr:"نظام الوقود", severity:"high", causes:["Short to ground","FRP sensor faulty"], causesAr:["قصر أرضي","حساس FRP تالف"], solution:"Check FRP sensor wiring for short", solutionAr:"فحص أسلاك حساس FRP للقصر", relatedSensors:["FRP Sensor"], affectedComponents:["Fuel Rail Pressure Sensor"], affectedComponentsAr:["حساس ضغط رامب الوقود"], safeToRide:false, estimatedRepairCost:{min:200,max:1000,currency:"SAR"} },
  "P0193": { code:"P0193", description:"Fuel Rail Pressure Sensor Circuit High Input", descriptionAr:"إشارة مرتفعة من حساس ضغط رامب الوقود", system:"engine", subsystem:"Fuel System", subsystemAr:"نظام الوقود", severity:"high", causes:["Open circuit","FRP sensor faulty"], causesAr:["دائرة مفتوحة","حساس FRP تالف"], solution:"Check FRP sensor wiring for open circuit", solutionAr:"فحص أسلاك حساس FRP للدائرة المفتوحة", relatedSensors:["FRP Sensor"], affectedComponents:["Fuel Rail Pressure Sensor"], affectedComponentsAr:["حساس ضغط رامب الوقود"], safeToRide:false, estimatedRepairCost:{min:200,max:1000,currency:"SAR"} },
  "P0194": { code:"P0194", description:"Fuel Rail Pressure Sensor Circuit Intermittent", descriptionAr:"إشارة متقطعة من حساس ضغط رامب الوقود", system:"engine", subsystem:"Fuel System", subsystemAr:"نظام الوقود", severity:"medium", causes:["Loose FRP connector","Intermittent wiring"], causesAr:["موصل FRP غير محكم","أسلاك متقطعة"], solution:"Check FRP connector and wiring", solutionAr:"فحص موصل وأسلاك FRP", relatedSensors:["FRP Sensor"], affectedComponents:["Fuel Rail Pressure Sensor"], affectedComponentsAr:["حساس ضغط رامب الوقود"], safeToRide:false, estimatedRepairCost:{min:200,max:1000,currency:"SAR"} },

  // ══════════════════════════════════════════════
  // P0200–P0219 — حاقنات الوقود
  // ══════════════════════════════════════════════
  "P0200": { code:"P0200", description:"Injector Circuit Malfunction", descriptionAr:"عطل في دائرة حاقنات الوقود", system:"engine", subsystem:"Fuel Injectors", subsystemAr:"حاقنات الوقود", severity:"high", causes:["Injector wiring fault","PCM driver fault","Multiple injector failure"], causesAr:["عطل أسلاك الحاقنات","عطل مشغّل PCM","تعطل عدة حاقنات"], solution:"Check injector wiring and resistance, test PCM drivers", solutionAr:"فحص أسلاك ومقاومة الحاقنات، اختبار مشغّلات PCM", relatedSensors:["Injector Circuit"], affectedComponents:["Fuel Injectors","PCM"], affectedComponentsAr:["حاقنات الوقود","وحدة PCM"], safeToRide:false, estimatedRepairCost:{min:300,max:3000,currency:"SAR"} },
  "P0201": { code:"P0201", description:"Injector Circuit Malfunction Cylinder 1", descriptionAr:"عطل في دائرة حاقن الأسطوانة 1", system:"engine", subsystem:"Fuel Injectors", subsystemAr:"حاقنات الوقود", severity:"high", causes:["Injector 1 faulty","Wiring fault cyl 1","PCM driver fault"], causesAr:["حاقن الأسطوانة 1 تالف","عطل أسلاك الأسطوانة 1","عطل مشغّل PCM"], solution:"Test injector 1 resistance (10-18 ohms), check wiring", solutionAr:"قياس مقاومة حاقن الأسطوانة 1 (10-18 أوم)، فحص الأسلاك", relatedSensors:["Injector 1"], affectedComponents:["Injector 1"], affectedComponentsAr:["حاقن الأسطوانة 1"], safeToRide:false, estimatedRepairCost:{min:200,max:1500,currency:"SAR"} },
  "P0202": { code:"P0202", description:"Injector Circuit Malfunction Cylinder 2", descriptionAr:"عطل في دائرة حاقن الأسطوانة 2", system:"engine", subsystem:"Fuel Injectors", subsystemAr:"حاقنات الوقود", severity:"high", causes:["Injector 2 faulty","Wiring fault cyl 2"], causesAr:["حاقن الأسطوانة 2 تالف","عطل أسلاك الأسطوانة 2"], solution:"Test injector 2 resistance, check wiring", solutionAr:"قياس مقاومة حاقن الأسطوانة 2، فحص الأسلاك", relatedSensors:["Injector 2"], affectedComponents:["Injector 2"], affectedComponentsAr:["حاقن الأسطوانة 2"], safeToRide:false, estimatedRepairCost:{min:200,max:1500,currency:"SAR"} },
  "P0203": { code:"P0203", description:"Injector Circuit Malfunction Cylinder 3", descriptionAr:"عطل في دائرة حاقن الأسطوانة 3", system:"engine", subsystem:"Fuel Injectors", subsystemAr:"حاقنات الوقود", severity:"high", causes:["Injector 3 faulty","Wiring fault cyl 3"], causesAr:["حاقن الأسطوانة 3 تالف","عطل أسلاك الأسطوانة 3"], solution:"Test injector 3 resistance, check wiring", solutionAr:"قياس مقاومة حاقن الأسطوانة 3، فحص الأسلاك", relatedSensors:["Injector 3"], affectedComponents:["Injector 3"], affectedComponentsAr:["حاقن الأسطوانة 3"], safeToRide:false, estimatedRepairCost:{min:200,max:1500,currency:"SAR"} },
  "P0204": { code:"P0204", description:"Injector Circuit Malfunction Cylinder 4", descriptionAr:"عطل في دائرة حاقن الأسطوانة 4", system:"engine", subsystem:"Fuel Injectors", subsystemAr:"حاقنات الوقود", severity:"high", causes:["Injector 4 faulty","Wiring fault cyl 4"], causesAr:["حاقن الأسطوانة 4 تالف","عطل أسلاك الأسطوانة 4"], solution:"Test injector 4 resistance, check wiring", solutionAr:"قياس مقاومة حاقن الأسطوانة 4، فحص الأسلاك", relatedSensors:["Injector 4"], affectedComponents:["Injector 4"], affectedComponentsAr:["حاقن الأسطوانة 4"], safeToRide:false, estimatedRepairCost:{min:200,max:1500,currency:"SAR"} },
  "P0205": { code:"P0205", description:"Injector Circuit Malfunction Cylinder 5", descriptionAr:"عطل في دائرة حاقن الأسطوانة 5", system:"engine", subsystem:"Fuel Injectors", subsystemAr:"حاقنات الوقود", severity:"high", causes:["Injector 5 faulty","Wiring fault cyl 5"], causesAr:["حاقن الأسطوانة 5 تالف","عطل أسلاك الأسطوانة 5"], solution:"Test injector 5 resistance, check wiring", solutionAr:"قياس مقاومة حاقن الأسطوانة 5، فحص الأسلاك", relatedSensors:["Injector 5"], affectedComponents:["Injector 5"], affectedComponentsAr:["حاقن الأسطوانة 5"], safeToRide:false, estimatedRepairCost:{min:200,max:1500,currency:"SAR"} },
  "P0206": { code:"P0206", description:"Injector Circuit Malfunction Cylinder 6", descriptionAr:"عطل في دائرة حاقن الأسطوانة 6", system:"engine", subsystem:"Fuel Injectors", subsystemAr:"حاقنات الوقود", severity:"high", causes:["Injector 6 faulty","Wiring fault cyl 6"], causesAr:["حاقن الأسطوانة 6 تالف","عطل أسلاك الأسطوانة 6"], solution:"Test injector 6 resistance, check wiring", solutionAr:"قياس مقاومة حاقن الأسطوانة 6، فحص الأسلاك", relatedSensors:["Injector 6"], affectedComponents:["Injector 6"], affectedComponentsAr:["حاقن الأسطوانة 6"], safeToRide:false, estimatedRepairCost:{min:200,max:1500,currency:"SAR"} },
  "P0207": { code:"P0207", description:"Injector Circuit Malfunction Cylinder 7", descriptionAr:"عطل في دائرة حاقن الأسطوانة 7", system:"engine", subsystem:"Fuel Injectors", subsystemAr:"حاقنات الوقود", severity:"high", causes:["Injector 7 faulty"], causesAr:["حاقن الأسطوانة 7 تالف"], solution:"Test injector 7", solutionAr:"اختبار حاقن الأسطوانة 7", relatedSensors:["Injector 7"], affectedComponents:["Injector 7"], affectedComponentsAr:["حاقن الأسطوانة 7"], safeToRide:false, estimatedRepairCost:{min:200,max:1500,currency:"SAR"} },
  "P0208": { code:"P0208", description:"Injector Circuit Malfunction Cylinder 8", descriptionAr:"عطل في دائرة حاقن الأسطوانة 8", system:"engine", subsystem:"Fuel Injectors", subsystemAr:"حاقنات الوقود", severity:"high", causes:["Injector 8 faulty"], causesAr:["حاقن الأسطوانة 8 تالف"], solution:"Test injector 8", solutionAr:"اختبار حاقن الأسطوانة 8", relatedSensors:["Injector 8"], affectedComponents:["Injector 8"], affectedComponentsAr:["حاقن الأسطوانة 8"], safeToRide:false, estimatedRepairCost:{min:200,max:1500,currency:"SAR"} },

  // ══════════════════════════════════════════════
  // P0220–P0229 — حساس موضع الخانق TPS (ثانوي)
  // ══════════════════════════════════════════════
  "P0220": { code:"P0220", description:"Throttle/Pedal Position Sensor B Circuit Malfunction", descriptionAr:"عطل في دائرة حساس موضع الخانق/الدواسة B", system:"engine", subsystem:"Throttle System", subsystemAr:"نظام الخانق", severity:"high", causes:["TPS B faulty","Wiring fault","PCM fault"], causesAr:["حساس TPS B تالف","عطل أسلاك","عطل PCM"], solution:"Test TPS B sensor and wiring", solutionAr:"اختبار حساس TPS B والأسلاك", relatedSensors:["TPS B"], affectedComponents:["Throttle Position Sensor B"], affectedComponentsAr:["حساس موضع الخانق B"], safeToRide:false, estimatedRepairCost:{min:200,max:1200,currency:"SAR"} },
  "P0221": { code:"P0221", description:"Throttle/Pedal Position Sensor B Range/Performance", descriptionAr:"أداء حساس موضع الخانق B خارج النطاق", system:"engine", subsystem:"Throttle System", subsystemAr:"نظام الخانق", severity:"high", causes:["TPS B out of range","Throttle body dirty"], causesAr:["حساس TPS B خارج النطاق","جسم خانق متسخ"], solution:"Clean throttle body, test TPS B", solutionAr:"تنظيف جسم الخانق، اختبار TPS B", relatedSensors:["TPS B"], affectedComponents:["Throttle Body","TPS B"], affectedComponentsAr:["جسم الخانق","حساس TPS B"], safeToRide:false, estimatedRepairCost:{min:200,max:1200,currency:"SAR"} },
  "P0222": { code:"P0222", description:"Throttle/Pedal Position Sensor B Circuit Low Input", descriptionAr:"إشارة منخفضة من حساس موضع الخانق B", system:"engine", subsystem:"Throttle System", subsystemAr:"نظام الخانق", severity:"high", causes:["Short to ground TPS B","TPS B faulty"], causesAr:["قصر أرضي TPS B","حساس TPS B تالف"], solution:"Check TPS B wiring for short to ground", solutionAr:"فحص أسلاك TPS B للقصر الأرضي", relatedSensors:["TPS B"], affectedComponents:["TPS B"], affectedComponentsAr:["حساس موضع الخانق B"], safeToRide:false, estimatedRepairCost:{min:200,max:1200,currency:"SAR"} },
  "P0223": { code:"P0223", description:"Throttle/Pedal Position Sensor B Circuit High Input", descriptionAr:"إشارة مرتفعة من حساس موضع الخانق B", system:"engine", subsystem:"Throttle System", subsystemAr:"نظام الخانق", severity:"high", causes:["Open circuit TPS B","TPS B faulty"], causesAr:["دائرة مفتوحة TPS B","حساس TPS B تالف"], solution:"Check TPS B wiring for open circuit", solutionAr:"فحص أسلاك TPS B للدائرة المفتوحة", relatedSensors:["TPS B"], affectedComponents:["TPS B"], affectedComponentsAr:["حساس موضع الخانق B"], safeToRide:false, estimatedRepairCost:{min:200,max:1200,currency:"SAR"} },

  // ══════════════════════════════════════════════
  // P0230–P0239 — طرمبة الوقود
  // ══════════════════════════════════════════════
  "P0230": { code:"P0230", description:"Fuel Pump Primary Circuit Malfunction", descriptionAr:"عطل في الدائرة الرئيسية لطرمبة الوقود", system:"engine", subsystem:"Fuel System", subsystemAr:"نظام الوقود", severity:"high", causes:["Fuel pump relay faulty","Wiring fault","PCM fault"], causesAr:["ريلاي طرمبة الوقود تالف","عطل أسلاك","عطل PCM"], solution:"Check fuel pump relay and wiring", solutionAr:"فحص ريلاي طرمبة الوقود والأسلاك", relatedSensors:["Fuel Pump Circuit"], affectedComponents:["Fuel Pump Relay","Fuel Pump"], affectedComponentsAr:["ريلاي طرمبة الوقود","طرمبة الوقود"], safeToRide:false, estimatedRepairCost:{min:200,max:1500,currency:"SAR"} },
  "P0231": { code:"P0231", description:"Fuel Pump Secondary Circuit Low", descriptionAr:"جهد منخفض في الدائرة الثانوية لطرمبة الوقود", system:"engine", subsystem:"Fuel System", subsystemAr:"نظام الوقود", severity:"high", causes:["Fuel pump faulty","Wiring short to ground","Relay fault"], causesAr:["طرمبة وقود تالفة","قصر أرضي في الأسلاك","عطل ريلاي"], solution:"Test fuel pump circuit, check relay", solutionAr:"اختبار دائرة طرمبة الوقود وفحص الريلاي", relatedSensors:["Fuel Pump Circuit"], affectedComponents:["Fuel Pump"], affectedComponentsAr:["طرمبة الوقود"], safeToRide:false, estimatedRepairCost:{min:300,max:2000,currency:"SAR"} },
  "P0232": { code:"P0232", description:"Fuel Pump Secondary Circuit High", descriptionAr:"جهد مرتفع في الدائرة الثانوية لطرمبة الوقود", system:"engine", subsystem:"Fuel System", subsystemAr:"نظام الوقود", severity:"high", causes:["Short to power","Relay stuck closed"], causesAr:["قصر للطاقة","ريلاي عالق مغلق"], solution:"Check fuel pump circuit for short to power", solutionAr:"فحص دائرة طرمبة الوقود للقصر للطاقة", relatedSensors:["Fuel Pump Circuit"], affectedComponents:["Fuel Pump Relay"], affectedComponentsAr:["ريلاي طرمبة الوقود"], safeToRide:false, estimatedRepairCost:{min:200,max:1000,currency:"SAR"} },

  // ══════════════════════════════════════════════
  // P0261–P0299 — حاقنات (أعطال إضافية)
  // ══════════════════════════════════════════════
  "P0261": { code:"P0261", description:"Cylinder 1 Injector Circuit Low", descriptionAr:"جهد منخفض في دائرة حاقن الأسطوانة 1", system:"engine", subsystem:"Fuel Injectors", subsystemAr:"حاقنات الوقود", severity:"high", causes:["Injector 1 short to ground","PCM driver fault"], causesAr:["قصر أرضي في حاقن الأسطوانة 1","عطل مشغّل PCM"], solution:"Check injector 1 wiring for short to ground", solutionAr:"فحص أسلاك حاقن الأسطوانة 1 للقصر الأرضي", relatedSensors:["Injector 1"], affectedComponents:["Injector 1"], affectedComponentsAr:["حاقن الأسطوانة 1"], safeToRide:false, estimatedRepairCost:{min:200,max:1500,currency:"SAR"} },
  "P0262": { code:"P0262", description:"Cylinder 1 Injector Circuit High", descriptionAr:"جهد مرتفع في دائرة حاقن الأسطوانة 1", system:"engine", subsystem:"Fuel Injectors", subsystemAr:"حاقنات الوقود", severity:"high", causes:["Injector 1 short to power","Open circuit"], causesAr:["قصر للطاقة في حاقن الأسطوانة 1","دائرة مفتوحة"], solution:"Check injector 1 wiring", solutionAr:"فحص أسلاك حاقن الأسطوانة 1", relatedSensors:["Injector 1"], affectedComponents:["Injector 1"], affectedComponentsAr:["حاقن الأسطوانة 1"], safeToRide:false, estimatedRepairCost:{min:200,max:1500,currency:"SAR"} },
  "P0264": { code:"P0264", description:"Cylinder 2 Injector Circuit Low", descriptionAr:"جهد منخفض في دائرة حاقن الأسطوانة 2", system:"engine", subsystem:"Fuel Injectors", subsystemAr:"حاقنات الوقود", severity:"high", causes:["Injector 2 short to ground"], causesAr:["قصر أرضي في حاقن الأسطوانة 2"], solution:"Check injector 2 wiring for short to ground", solutionAr:"فحص أسلاك حاقن الأسطوانة 2 للقصر الأرضي", relatedSensors:["Injector 2"], affectedComponents:["Injector 2"], affectedComponentsAr:["حاقن الأسطوانة 2"], safeToRide:false, estimatedRepairCost:{min:200,max:1500,currency:"SAR"} },
  "P0265": { code:"P0265", description:"Cylinder 2 Injector Circuit High", descriptionAr:"جهد مرتفع في دائرة حاقن الأسطوانة 2", system:"engine", subsystem:"Fuel Injectors", subsystemAr:"حاقنات الوقود", severity:"high", causes:["Injector 2 short to power"], causesAr:["قصر للطاقة في حاقن الأسطوانة 2"], solution:"Check injector 2 wiring", solutionAr:"فحص أسلاك حاقن الأسطوانة 2", relatedSensors:["Injector 2"], affectedComponents:["Injector 2"], affectedComponentsAr:["حاقن الأسطوانة 2"], safeToRide:false, estimatedRepairCost:{min:200,max:1500,currency:"SAR"} },
  "P0267": { code:"P0267", description:"Cylinder 3 Injector Circuit Low", descriptionAr:"جهد منخفض في دائرة حاقن الأسطوانة 3", system:"engine", subsystem:"Fuel Injectors", subsystemAr:"حاقنات الوقود", severity:"high", causes:["Injector 3 short to ground"], causesAr:["قصر أرضي في حاقن الأسطوانة 3"], solution:"Check injector 3 wiring for short", solutionAr:"فحص أسلاك حاقن الأسطوانة 3 للقصر", relatedSensors:["Injector 3"], affectedComponents:["Injector 3"], affectedComponentsAr:["حاقن الأسطوانة 3"], safeToRide:false, estimatedRepairCost:{min:200,max:1500,currency:"SAR"} },
  "P0268": { code:"P0268", description:"Cylinder 3 Injector Circuit High", descriptionAr:"جهد مرتفع في دائرة حاقن الأسطوانة 3", system:"engine", subsystem:"Fuel Injectors", subsystemAr:"حاقنات الوقود", severity:"high", causes:["Injector 3 short to power"], causesAr:["قصر للطاقة في حاقن الأسطوانة 3"], solution:"Check injector 3 wiring", solutionAr:"فحص أسلاك حاقن الأسطوانة 3", relatedSensors:["Injector 3"], affectedComponents:["Injector 3"], affectedComponentsAr:["حاقن الأسطوانة 3"], safeToRide:false, estimatedRepairCost:{min:200,max:1500,currency:"SAR"} },
  "P0270": { code:"P0270", description:"Cylinder 4 Injector Circuit Low", descriptionAr:"جهد منخفض في دائرة حاقن الأسطوانة 4", system:"engine", subsystem:"Fuel Injectors", subsystemAr:"حاقنات الوقود", severity:"high", causes:["Injector 4 short to ground"], causesAr:["قصر أرضي في حاقن الأسطوانة 4"], solution:"Check injector 4 wiring for short", solutionAr:"فحص أسلاك حاقن الأسطوانة 4 للقصر", relatedSensors:["Injector 4"], affectedComponents:["Injector 4"], affectedComponentsAr:["حاقن الأسطوانة 4"], safeToRide:false, estimatedRepairCost:{min:200,max:1500,currency:"SAR"} },
  "P0271": { code:"P0271", description:"Cylinder 4 Injector Circuit High", descriptionAr:"جهد مرتفع في دائرة حاقن الأسطوانة 4", system:"engine", subsystem:"Fuel Injectors", subsystemAr:"حاقنات الوقود", severity:"high", causes:["Injector 4 short to power"], causesAr:["قصر للطاقة في حاقن الأسطوانة 4"], solution:"Check injector 4 wiring", solutionAr:"فحص أسلاك حاقن الأسطوانة 4", relatedSensors:["Injector 4"], affectedComponents:["Injector 4"], affectedComponentsAr:["حاقن الأسطوانة 4"], safeToRide:false, estimatedRepairCost:{min:200,max:1500,currency:"SAR"} },
  "P0273": { code:"P0273", description:"Cylinder 5 Injector Circuit Low", descriptionAr:"جهد منخفض في دائرة حاقن الأسطوانة 5", system:"engine", subsystem:"Fuel Injectors", subsystemAr:"حاقنات الوقود", severity:"high", causes:["Injector 5 short to ground"], causesAr:["قصر أرضي في حاقن الأسطوانة 5"], solution:"Check injector 5 wiring for short", solutionAr:"فحص أسلاك حاقن الأسطوانة 5 للقصر", relatedSensors:["Injector 5"], affectedComponents:["Injector 5"], affectedComponentsAr:["حاقن الأسطوانة 5"], safeToRide:false, estimatedRepairCost:{min:200,max:1500,currency:"SAR"} },
  "P0276": { code:"P0276", description:"Cylinder 6 Injector Circuit Low", descriptionAr:"جهد منخفض في دائرة حاقن الأسطوانة 6", system:"engine", subsystem:"Fuel Injectors", subsystemAr:"حاقنات الوقود", severity:"high", causes:["Injector 6 short to ground"], causesAr:["قصر أرضي في حاقن الأسطوانة 6"], solution:"Check injector 6 wiring for short", solutionAr:"فحص أسلاك حاقن الأسطوانة 6 للقصر", relatedSensors:["Injector 6"], affectedComponents:["Injector 6"], affectedComponentsAr:["حاقن الأسطوانة 6"], safeToRide:false, estimatedRepairCost:{min:200,max:1500,currency:"SAR"} },

  // ══════════════════════════════════════════════
  // P0300–P0312 — أكواد الاحتراق (Misfire)
  // ══════════════════════════════════════════════
  "P0300": { code:"P0300", description:"Random/Multiple Cylinder Misfire Detected", descriptionAr:"احتراق غير منتظم في أسطوانات متعددة", system:"engine", subsystem:"Ignition", subsystemAr:"نظام الإشعال", severity:"critical", causes:["Spark plugs worn","Ignition coils faulty","Injectors leaking","Low compression","Timing issue"], causesAr:["بواجي متآكلة","كويلات إشعال تالفة","حاقنات تسرب","ضغط منخفض","مشكلة توقيت"], solution:"Check spark plugs, ignition coils, injectors, and compression", solutionAr:"فحص البواجي والكويلات والحاقنات وضغط الأسطوانات", relatedSensors:["CKP Sensor","CMP Sensor"], affectedComponents:["Spark Plugs","Ignition Coils","Fuel Injectors"], affectedComponentsAr:["البواجي","كويلات الإشعال","حاقنات الوقود"], safeToRide:false, estimatedRepairCost:{min:200,max:5000,currency:"SAR"} },
};
